= Returning GeoTiff and JPEG2000
:Leonard Porrello <lporrel@gmail.com>:
{docdate}
:numbered:
:toc:

== Introduction

The File Out GDAL module provides the ability to return various kinds of
GIS data files as responses from Hyrax. The handler currently supports
returning GeoTIFF and JPEG2000 files. Not every dataset served by Hyrax
can be returned as a GIS dataset, either because it lacks
latitude/longitude information or because it is not organized so that
the latitude and longitude values are recognized by this module.

Most GIS data include information about their coordinate reference
systems, but how that information is encoded can vary widely. This
handler looks for geographical information that follows the CF-1.4
standard for [grid mappings and projections
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#grid-mappings-and-projections]
(note that the link is actually to the CF-1.6 standard; it seems the
CF-1.4 site from LLNL is no longer available). It will recognize either
the EPSG:4047 or WGS84 Geographical Coordinate systems (GCS) and
provides an option to set the default GCS using a parameter (described
below).

== Services Handled

This module does not handle any services but adds to an existing service

== Services Provided

The module provides an additional format to the `dap` service's `dods`
command. The format is used to specify a "returnAs" format. This module
provides the additional format of returning the OPenDAP data object as a
GeoTIFF or JPEG2000 file.

== How to Use the Module

Once installed, the _fong.conf_ file is installed in the BES
etc/bes/modules directory and is automatically loaded by the BES at
startup. There is a configuration option that you can change for this
module. The _FONg.Tempdir' parameter in the_ fong.conf _configuration
file tells the module where to store the files generated by the module
until the file is streamed back to the caller. The default value for
this parameter is the /tmp directory. You should change this to a
location where there is plenty of disk space/quota that is owned by the
user set to run the BES._

-----------------
FONg.Tempdir=/tmp
-----------------

The next time the BES is started it will load this module. And, once
installed, the OLFS will know that it can use this module to transform
your data. You can get GeoTIFF or JPEG2000 responses for applicable
datasets by appending the extensions _.tiff_ or _.jp2_ to the dataset's
OpenDAP URL.

If not using the OLFS to serve your data, for example if using the
bescmdln, you would run a command file that would look something like
this:

--------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<request reqID="some_unique_value" >
    <setContext name="dap_format">dap2</setContext>
    <setContainer name="c" space="catalog">data/nc/coads_climatology.nc</setContainer>
    <define name="d">
    <container name="c" />
    </define>
    <get type="dods" definition="d" returnAs="tiff"/>
</request>
--------------------------------------------------------------------------------------

In addition to setting the directory where the response file is
initially built, you can use the _FONg.default_gcs_ configuration
parameter to set the default Geographical Coordinate System (GCS) for
the handler. This GCS will be used when the dataset's metadata does not
provide information GCS that the handler can recognize.
