BES - Debugging Using besstandalone - OPeNDAP Documentation
===========================================================

[[firstHeading]]
BES - Debugging Using besstandalone
-----------------------------------

From OPeNDAP Documentation

When you need to debug a handler, there are several ways to go about it.
First, you can use a run-time debugger like the one included with
Eclipse (really GNU's __gdb__), fall back on the tried and true 'print
statements' or some other combination of program instrumentation and
run-time diagnosis. In all cases, being able to run your handler _as
part of a command line program_ and not a server, will speed up and
simplify the process.

We have designed a run-time debugging tool for just this purpose.

Contents
~~~~~~~~

* #Review:_Debugging_using_a_client_and_the_server[1 Review: Debugging
using a client and the server]
* link:#What_you_would_like[2 What you would like]
* link:#Examples[3 Examples]
* link:#Some_Tricks[4 Some Tricks]
** link:#Using_besstandalone_and_the_BESDEBUG_instrumentation_macro[4.1
Using besstandalone and the BESDEBUG instrumentation macro]
** link:#Filtering_binary_output_using_getdap[4.2 Filtering binary
output using getdap]

1 Review: Debugging using a client and the server
-------------------------------------------------

To test (and/or debug) your handler using the BES (server), you first
build and install your new handler version. Then you modify the
_bes.conf_ file so that the handler will be loaded at run-time and start
the server. Next you start up the _bescmdln_ client and point it at the
server using the hostname (likely __localhost__) and port number (again,
likely the default of __10022__). You can issue commands directly to
_bescmdln_ or pass it the name of a file of commands to run in sequence.
Either way bescmdln prints whatever it get back from the BES to standard
output.

2 What you would like
---------------------

It would be far easier to be be able to run you handler as if it _was_
the command line client and see the output directly. This is exactly
what the command _besstandalone_ does for you. Like the _besctl start_
command, _besstandalone_ reads an optional _bes.config_ file and takes
optional debugging switches. Unlike _besctl_ it does not start a server
but, after performing the server initialization routines, it switches to
'client mode' and reads commands, printing the response from the BES
_plus_ any debugging output that was generated.

The command files used by _bescmdln_ and _besstandalone_ are identical,
so files developed for one can be used with the other.

3 Examples
----------

A sample command file that asks the BES for a DDS response (from
$prefix/src/modules/hdf4_handler/bes-testsuite):

code,de1---------------------------------------------------------------------------------------
code,de1
<?xml version="1.0" encoding="UTF-8"?>
<request reqID="some_unique_value" >
    <setContext name="dap_format">dap2</setContext>
    <setContainer name="data" space="catalog">/data/1990-S1700101.HDF.gz</setContainer>
    <define name="d">
    <container name="data" />
    </define>
    <get type="dds" definition="d" />
</request>
---------------------------------------------------------------------------------------

Here's how to run these commands using the server and __bescmdln__:

Invalid language.

You need to specify a language like this: <source
lang="html4strict">...</source>

Supported languages for syntax highlighting:

4cs, 6502acme, 6502kickass, 6502tasm, 68000devpac, abap, actionscript,
actionscript3, ada, algol68, apache, applescript, apt_sources, arm, asm,
asp, asymptote, autoconf, autohotkey, autoit, avisynth, awk, bascomavr,
bash, basic4gl, bf, bibtex, blitzbasic, bnf, boo, c, c_loadrunner,
c_mac, caddcl, cadlisp, cfdg, cfm, chaiscript, cil, clojure, cmake,
cobol, coffeescript, cpp, cpp-qt, csharp, css, cuesheet, d, dcl, dcpu16,
dcs, delphi, diff, div, dos, dot, e, ecmascript, eiffel, email, epc,
erlang, euphoria, f1, falcon, fo, fortran, freebasic, freeswitch,
fsharp, gambas, gdb, genero, genie, gettext, glsl, gml, gnuplot, go,
groovy, gwbasic, haskell, haxe, hicest, hq9plus, html4strict, html5,
icon, idl, ini, inno, intercal, io, j, java, java5, javascript, jquery,
kixtart, klonec, klonecpp, latex, lb, ldif, lisp, llvm, locobasic,
logtalk, lolcode, lotusformulas, lotusscript, lscript, lsl2, lua, m68k,
magiksf, make, mapbasic, matlab, mirc, mmix, modula2, modula3, mpasm,
mxml, mysql, nagios, netrexx, newlisp, nsis, oberon2, objc, objeck,
ocaml, ocaml-brief, octave, oobas, oorexx, oracle11, oracle8, oxygene,
oz, parasail, parigp, pascal, pcre, per, perl, perl6, pf, php,
php-brief, pic16, pike, pixelbender, pli, plsql, postgresql, povray,
powerbuilder, powershell, proftpd, progress, prolog, properties,
providex, purebasic, pycon, pys60, python, q, qbasic, rails, rebol, reg,
rexx, robots, rpmspec, rsplus, ruby, sas, scala, scheme, scilab,
sdlbasic, smalltalk, smarty, spark, sparql, sql, stonescript,
systemverilog, tcl, teraterm, text, thinbasic, tsql, typoscript, unicon,
upc, urbi, uscript, vala, vb, vbnet, vedit, verilog, vhdl, vim,
visualfoxpro, visualprolog, whitespace, whois, winbatch, xbasic, xml,
xorg_conf, xpp, yaml, z80, zxbasic

 +

--------------------------------------------------------------
besctl start

bescmdln -h localhost -p 10022 -i 1990-S1700101.HDF.dds.bescmd
--------------------------------------------------------------

Here's the version using besstandalone:

Invalid language.

You need to specify a language like this: <source
lang="html4strict">...</source>

Supported languages for syntax highlighting:

4cs, 6502acme, 6502kickass, 6502tasm, 68000devpac, abap, actionscript,
actionscript3, ada, algol68, apache, applescript, apt_sources, arm, asm,
asp, asymptote, autoconf, autohotkey, autoit, avisynth, awk, bascomavr,
bash, basic4gl, bf, bibtex, blitzbasic, bnf, boo, c, c_loadrunner,
c_mac, caddcl, cadlisp, cfdg, cfm, chaiscript, cil, clojure, cmake,
cobol, coffeescript, cpp, cpp-qt, csharp, css, cuesheet, d, dcl, dcpu16,
dcs, delphi, diff, div, dos, dot, e, ecmascript, eiffel, email, epc,
erlang, euphoria, f1, falcon, fo, fortran, freebasic, freeswitch,
fsharp, gambas, gdb, genero, genie, gettext, glsl, gml, gnuplot, go,
groovy, gwbasic, haskell, haxe, hicest, hq9plus, html4strict, html5,
icon, idl, ini, inno, intercal, io, j, java, java5, javascript, jquery,
kixtart, klonec, klonecpp, latex, lb, ldif, lisp, llvm, locobasic,
logtalk, lolcode, lotusformulas, lotusscript, lscript, lsl2, lua, m68k,
magiksf, make, mapbasic, matlab, mirc, mmix, modula2, modula3, mpasm,
mxml, mysql, nagios, netrexx, newlisp, nsis, oberon2, objc, objeck,
ocaml, ocaml-brief, octave, oobas, oorexx, oracle11, oracle8, oxygene,
oz, parasail, parigp, pascal, pcre, per, perl, perl6, pf, php,
php-brief, pic16, pike, pixelbender, pli, plsql, postgresql, povray,
powerbuilder, powershell, proftpd, progress, prolog, properties,
providex, purebasic, pycon, pys60, python, q, qbasic, rails, rebol, reg,
rexx, robots, rpmspec, rsplus, ruby, sas, scala, scheme, scilab,
sdlbasic, smalltalk, smarty, spark, sparql, sql, stonescript,
systemverilog, tcl, teraterm, text, thinbasic, tsql, typoscript, unicon,
upc, urbi, uscript, vala, vb, vbnet, vedit, verilog, vhdl, vim,
visualfoxpro, visualprolog, whitespace, whois, winbatch, xbasic, xml,
xorg_conf, xpp, yaml, z80, zxbasic

 +

---------------------------------------------------------
besstandalone -c bes.conf -i 1990-S1700101.HDF.dds.bescmd
---------------------------------------------------------

Note that if you try this you will see that most of the regression tests
use bes command files that reference local data and the paths are a bit
different than when those same data sets are installed in a running
server.

4 Some Tricks
-------------

4.1 Using besstandalone and the BESDEBUG instrumentation macro
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The BES supports a flexible run-time instrumentation system that you can
access using besstandalone.
Here's an example of instrumentation:

code,de1--------------------------------------------------------------------
code,de1
void
HDF4Module::initialize(const string & modname)
{
    BESDEBUG("h4", "Initializing HDF4 module " << modname << endl) ;
 
    BESRequestHandler *handler = new HDF4RequestHandler(modname);
    BESRequestHandlerList::TheList()->add_handler(modname, handler);
 
    ...
--------------------------------------------------------------------

The instrumentation macro is __BESDEBUG__. To 'turn on' this and see the
output, start _besstandalone_ using the _-d_ option. When you specify
the debug option, you need to provide one argument which names the
output sink for the debugging information and one or more 'selector
names'. An example will make things clearer. To see the output from the
above BESDEBUG call, you would pass this option to besstandalone: __-d
"cerr,h4"__. Here's how you would run it:

Invalid language.

You need to specify a language like this: <source
lang="html4strict">...</source>

Supported languages for syntax highlighting:

4cs, 6502acme, 6502kickass, 6502tasm, 68000devpac, abap, actionscript,
actionscript3, ada, algol68, apache, applescript, apt_sources, arm, asm,
asp, asymptote, autoconf, autohotkey, autoit, avisynth, awk, bascomavr,
bash, basic4gl, bf, bibtex, blitzbasic, bnf, boo, c, c_loadrunner,
c_mac, caddcl, cadlisp, cfdg, cfm, chaiscript, cil, clojure, cmake,
cobol, coffeescript, cpp, cpp-qt, csharp, css, cuesheet, d, dcl, dcpu16,
dcs, delphi, diff, div, dos, dot, e, ecmascript, eiffel, email, epc,
erlang, euphoria, f1, falcon, fo, fortran, freebasic, freeswitch,
fsharp, gambas, gdb, genero, genie, gettext, glsl, gml, gnuplot, go,
groovy, gwbasic, haskell, haxe, hicest, hq9plus, html4strict, html5,
icon, idl, ini, inno, intercal, io, j, java, java5, javascript, jquery,
kixtart, klonec, klonecpp, latex, lb, ldif, lisp, llvm, locobasic,
logtalk, lolcode, lotusformulas, lotusscript, lscript, lsl2, lua, m68k,
magiksf, make, mapbasic, matlab, mirc, mmix, modula2, modula3, mpasm,
mxml, mysql, nagios, netrexx, newlisp, nsis, oberon2, objc, objeck,
ocaml, ocaml-brief, octave, oobas, oorexx, oracle11, oracle8, oxygene,
oz, parasail, parigp, pascal, pcre, per, perl, perl6, pf, php,
php-brief, pic16, pike, pixelbender, pli, plsql, postgresql, povray,
powerbuilder, powershell, proftpd, progress, prolog, properties,
providex, purebasic, pycon, pys60, python, q, qbasic, rails, rebol, reg,
rexx, robots, rpmspec, rsplus, ruby, sas, scala, scheme, scilab,
sdlbasic, smalltalk, smarty, spark, sparql, sql, stonescript,
systemverilog, tcl, teraterm, text, thinbasic, tsql, typoscript, unicon,
upc, urbi, uscript, vala, vb, vbnet, vedit, verilog, vhdl, vim,
visualfoxpro, visualprolog, whitespace, whois, winbatch, xbasic, xml,
xorg_conf, xpp, yaml, z80, zxbasic

 +

----------------------------------------------------------------------
besstandalone -d "cerr,h4" -c bes.conf -i 1990-S1700101.HDF.dds.bescmd
----------------------------------------------------------------------

Of course, _cerr_ is C++'s standard error output sink; you can use
_cout_ or the name of a file instead. Also, you can list a number of
selectors, so your handler may have separate BESDEBUG calls for
initialization, run-time status, some tricky parts of the code, ...

4.2 Filtering binary output using getdap
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

One thing that's nice about DAP is that so many of the responses are
ASCII or XML. That makes them easy (relatively) to debug when compared
to binary outputs. But data is binary in most of these datasets and DAP
transmits it that way for obvious efficiency reasons. The _getdap_
command line client can be used to filter the binary data response
object returned by the bes so that the data values are rendered as ASCII
(but without using the server's ASCII output capability). Here's what
that looks like.

Given:

code,de1------------------------------------------------------------------------------
code,de1
<?xml version="1.0" encoding="UTF-8"?>
<request reqID="some_unique_value" >
    <setContext name="dap_format">dap2</setContext>
    <setContainer name="data" space="catalog">/data/foo2.hdf.gz</setContainer>
    <define name="d">
    <container name="data" />
    </define>
    <get type="dods" definition="d" />
</request>
------------------------------------------------------------------------------

Invalid language.

You need to specify a language like this: <source
lang="html4strict">...</source>

Supported languages for syntax highlighting:

4cs, 6502acme, 6502kickass, 6502tasm, 68000devpac, abap, actionscript,
actionscript3, ada, algol68, apache, applescript, apt_sources, arm, asm,
asp, asymptote, autoconf, autohotkey, autoit, avisynth, awk, bascomavr,
bash, basic4gl, bf, bibtex, blitzbasic, bnf, boo, c, c_loadrunner,
c_mac, caddcl, cadlisp, cfdg, cfm, chaiscript, cil, clojure, cmake,
cobol, coffeescript, cpp, cpp-qt, csharp, css, cuesheet, d, dcl, dcpu16,
dcs, delphi, diff, div, dos, dot, e, ecmascript, eiffel, email, epc,
erlang, euphoria, f1, falcon, fo, fortran, freebasic, freeswitch,
fsharp, gambas, gdb, genero, genie, gettext, glsl, gml, gnuplot, go,
groovy, gwbasic, haskell, haxe, hicest, hq9plus, html4strict, html5,
icon, idl, ini, inno, intercal, io, j, java, java5, javascript, jquery,
kixtart, klonec, klonecpp, latex, lb, ldif, lisp, llvm, locobasic,
logtalk, lolcode, lotusformulas, lotusscript, lscript, lsl2, lua, m68k,
magiksf, make, mapbasic, matlab, mirc, mmix, modula2, modula3, mpasm,
mxml, mysql, nagios, netrexx, newlisp, nsis, oberon2, objc, objeck,
ocaml, ocaml-brief, octave, oobas, oorexx, oracle11, oracle8, oxygene,
oz, parasail, parigp, pascal, pcre, per, perl, perl6, pf, php,
php-brief, pic16, pike, pixelbender, pli, plsql, postgresql, povray,
powerbuilder, powershell, proftpd, progress, prolog, properties,
providex, purebasic, pycon, pys60, python, q, qbasic, rails, rebol, reg,
rexx, robots, rpmspec, rsplus, ruby, sas, scala, scheme, scilab,
sdlbasic, smalltalk, smarty, spark, sparql, sql, stonescript,
systemverilog, tcl, teraterm, text, thinbasic, tsql, typoscript, unicon,
upc, urbi, uscript, vala, vb, vbnet, vedit, verilog, vhdl, vim,
visualfoxpro, visualprolog, whitespace, whois, winbatch, xbasic, xml,
xorg_conf, xpp, yaml, z80, zxbasic

 +

----------------------------------------------------------------------------
besstandalone -d "cerr,h4" -c bes.conf -i foo2.hdf.data.bescmd | getdap -M -
----------------------------------------------------------------------------

Where the option _-M_ tells getdap to strip off any MIME headers in the
response and the dash tells it to read from stdin.
