//= Hyrax - OLFS Configuration - OPeNDAP Documentation
//:Leonard Porrello <lporrel@gmail.com>:
//{docdate}
//:numbered:
//:toc:

[[OLFS-config]]
== OLFS Configuration

This document should help you get started configuring the OLFS web
application component of Hyrax.

Additionally the OLFS web application relies on one or more instances of the
<<bess-configuration, BES>> to provide it with
data access and basic catalog metadata.

The OLFS web application stores its configuration state in a number of
files. The server's configuration is altered by carefully modifying the
content of one or more of these files and then restarting the web
application (or simply restarting Tomcat).

[[OLFS-config-location]]
=== Location of the OLFS Configuration Files

Beginning with olfs-1.15.0 (part of hyrax-1.13.0) the OLFS will use the
following procedure to deterimine its configuration location:

. It will first look at the value of the user environment variable
`OLFS_CONFIG_DIR`. If the variable is set and its value is the pathname
of an existing directory that is readable and writable by Tomcat, the OLFS
will use it. Otherwise,
. If the directory `/etc/olfs` exists and is readable and writable by
Tomcat the OLFS will use it. Otherwise,
. If the directory `/usr/share/olfs` exists and is readable and writable
 by Tomcat then the OLFS will use it (this was added for Hyrax 1.14.1). Otherwise,
. The OLFS will utilize the default configuration bundled in the web
application web archive file (opendap.war).

In this way the OLFS can start without a persistent local configuration.
If the default configuration works for your intended use, then there is
no need create a persistent localized configuration. If changes need to
be made to the configuration, then it is *strongly recommended* that the
user enable the use of a persistent local configuration. This way
updating the web application won't destroy your changes. This is easily
done by creating an empty directory and identifying it with the
`OLFS_CONFIG_DIR` environment variable. For example:

----
export OLFS_CONFIG_DIR="/home/tomcat/hyrax"
----

Alternatively, you can create either the directory `/etc/olfs` or the
directory `/usr/share/olfs`. _Make sure that the directory you create is
both readable and writable by Tomcat._

Once the directory is created (and in the first case the environment
variable is set) restart the OLFS (Tomcat). This will cause the OLFS to
move a copy of its default configuration into the empty directory and
then utilize it. You can then edit the local copy.

==== CentOS-7.x and/or SELinux

SELinux (which is a special gift you get with CentOS-7) will cause some new challenges for those
not familiar with the changes it brings to the system environment. For one, Tomcat runs as a
_confined_ user. Here we'll examine how these changes affect the OLFS.

===== Localizing the OLFS Configuration under SELinux
When using a _yum_ installed Tomcat on CentOS-7.x (or any other Linux
environment that is essentially an *SELinux* variant), neither the `/etc/olfs`
or the `/usr/share/olfs` configuration locations will work without taking extra steps.
You must alter the SELinux access policies to give the Tomcat user
permission to read and write to one of these directories.

Here is a script/recipe for configuring the `/usr/share/olfs` directory for reading
and writing by the Tomcat user. There are probably a number of alternative ways to accomplish this,
but this one worked for me.
----
#!/bin/sh
# You must be the super user to do this stuff...
sudo -s

# Create the location for the local configuration
mkdir -p /usr/share/olfs

# Change the group ownership to the tomcat group.
# (SELinux will not allow you make the owner tomcat.)
chgrp tomcat /usr/share/olfs

# Make it writable by the tomcat group
sudo chmod g+w /usr/share/olfs

# Use semanage to change the context of the target
# directory and any (future) child dirs
semanage fcontext -a -t tomcat_var_lib_t "/usr/share/olfs(/.*)?"

# Use restorecon to commit/do the labeling.
restorecon -rv /usr/share/olfs
----
There is a lot going in the above script and to fully understand it you will need to study the man
pages for _semanage_ and _restorecon_. You may also get some benefit from these articles about
SELinux and the permissions issues therein:

https://wiki.centos.org/HowTos/SELinux

https://noobient.com/post/165842438861/selinux-crash-course

https://noobient.com/post/165972214381/selinux-woes-with-tomcat-on-centos-74

===== Tomcat Logs

In SELinux the _yum_ installed Tomcat does not produce a catalina.out file, rather that
output is sent to the *_journal_* and can be viewed with the command:
----
journalctl -u tomcat
----


=== OLFS Configuration Files

The OLFS web application gets its configuration from four files. In general
all of your configuration need will be met by making changes to the
first two: *olfs.xml* and *catalog.xml*

*olfs.xml* ::
  *Role*: Contains the primary OLFS configuration - BES(s) associations,
   directory view instructions, gateway service behavior options,
   static THREDDS catalog behavior, etc. +
  *Location:* In the persistent content directory which by default is
  located at _$CATALINA_HOME/content/opendap/_

*catalog.xml* ::
  *Role*: Master(top-level) THREDDS catalog content for static THREDDS
  catalogs. +
  *Location:* In the persistent content directory which by default is
  located at _$CATALINA_HOME/content/opendap/_

*viewers.xml* ::
  *Role*: Contains the localized Viewers configuration. +
  *Location:* In the persistent content directory which by default is
  located at _$CATALINA_HOME/content/opendap/_


=== *olfs.xml* Configuration File

The *olfs.xml* file contains the core configuration of the Hyrax
servlet:


==== OLFSConfig Element

The <__OLFSConfig__> element is the document root. It contains two
elements that suppy the configuration for the OLFS: <__BesManager__> and
<__DispatchHandlers__ >.

==== `<BESManager>` Element (required)

The BESManager element provides configuration for the BESManager class.
The BESManager is used 
//in various parts of the OLFS web application
whenever the software needs to access BES's services. This
configuration is key to the function of Hyrax, for in it 
is defined each BES that is connected to a Hyrax installation. The following examples
will show a single BES example. For more information on configuring Hyrax to use multiple BES's
<<config-hyrax-mult-BESs, look here>>.

Each BES is identified using a seperate <__BES__> child element inside
of the <__BESManager__> element.

===== `<BES>` Element (required)

The <__BES__> element provides the OLFS with connection and control
information for a BES. There are 4 child elements in a <__BES__>
element: <__prefix__>, <__host__>, <__port__>, and <__ClientPool__>.

===== `<prefix>` Element (required)

This child element of the <__BES__> element contains the URL prefix that
the OLFS will associate with this BES. This provides a mapping between
this BES to the URI space serviced by the OLFS. The prefix, then, is 
a token that is placed between the
_host:port/context/_ part of the Hyrax URL and the catalog root.
The catalog root is used to designate a particular BES instance in the
event that multiple BES's are available to a single OLFS.

For a single BES (the default configuration) the tag *must* be designated 
by "/". This prefix provides a mapping for each BES connected to the OLFS
and the URI space serviced by the OLFS.

. There *must* be at least one BES element in the BESManager 
handler configuration whose prefix has a value of "/" (see _example 1_).
There may be more than one <_BES_>, but only that one is required.
. For a single BES (the one with "/" as its prefix) no additional
effort is required; however, when using multiple BES's it is neccesary
that each BES has a mount point exposed as a directory (aka collection)
in the URI space where it's going to appear. See
<<config-hyrax-mult-BESs, Configuring With Multiple BES's>>
for more information.
. The prefix string *must* always begin with the slash ("/")
character. (See __example 2__.)

_Example 1:_

----
 <prefix>/</prefix>
----

_Example 2:_

----
 <prefix>/data/nc</prefix>
----

===== `<host>` Element (required)

This child element of the <__BES__> element contains the host name or IP
address of the BES.

_Example:_

----
<host>test.opendap.org</host>
----

===== `<port>` Element (required)

This child element of the <__BES__> element contains port number on
which the BES is listening.

_Example:_
----
<port>10022</port>
----

===== `<timeOut>` Element (optional)

This child element of the <__BES__> element contains the timeout time,
in seconds, for the OLFS to wait for this BES to respond. Defaults to 300
seconds.

_Example:_

----
<timeOut>600</timeOut >
----

===== `<maxResponseSize>` Element (optional)

This child element of the <__BES__> element contains in bytes
the maximum response size allowed for this BES. Requests that produce a
larger response will receive an error. A value of zero (_0_)
indicates that there is no imposed limit. The default value is 0.

_Example:_

---- 
<maxResponseSize>0</maxResponseSize>
----

===== `<ClientPool>` Element (optional)

This child element of the <__BES__> element configures the behavior of
the pool of client connections that the OLFS maintains with this
particular BES. These connections are pooled for efficiency and speed.
This element has two attributes: `maximum` and `maxCmds`.

The `maximum` attribute specifies the
maximum number of concurrent BES client connections that the OLFS can
make. The default value of `maximum` is 200.

The `maxCmds` attribute specifies the maximum number of commands that can be issued over a particular BESClient connection. The default is 2000.

_Example:_

---- 
<ClientPool maximum="200" maxCmds="2000" />
----

If the <ClientPool> element is missing, the pool (`maximum`) size defaults to 200 and `maxCmds` defaults to 2000.

===== `<adminPort>` element (optional)

This child element of the <__BES__> element contains the port on the BES
system that can be used by the Hyrax Admin Interface to control the BES.
THe BES must also be configured to open and utilize this admin port.

_Example:_

---- 
<adminPort>11002</adminPort>
----

===== Example BESManager Configuration Element

---- 
<BESManager>
    <BES>
        <prefix>/</prefix>
        <host>localhost</host>
        <port>10022</port>
        <timeOut>300</timeOut>
        <maxResponseSize>0</maxResponseSize>
        <ClientPool maximum="10" maxCmds="2000" />
    </BES>
</BESManager >
----



=== `<ThreddsService>`  (optional)
This configuration parameter controls

* The location of the static THREDDS catalog root in the server.
* If the static THREDDS catalogs are held in memory (faster) or read from disk for each request (slower).
* If the server will broker remote THREDDS catalogs and their data by following `thredds:catalogRef` links that point to THREDDS catalogs on other systems.

==== `<prefix>` attribute (optional)

Sets the name of the root of the static THREDDS catalogs in Hyrax.
For example, if the prefix is `thredds`,
then `http://localhost:8080/opendap/thredds/` should give you the
top-level static catalog (Typically the contents of the file
`/etc/olfs/opendap/catalog.xml`)

Default: `thredds`

==== `<useMemoryCache>` attribute (optional)

If the text value of this attribute is the string 'true,' this will cause
the servlet to ingest all of the static catalog files at startup and
hold their contents in memory. If set to false then then each request for a static THREDDS catalog will cause the server to read and parse the catalog from disk.
<<THREDDS-config, See this page for more information about the memory caching
operations.>>

Default: `true`

==== `<allowRemote>` attribute (optional)

If this attribute is present and it's value is set to true then the server will "broker"
remote THREDDS catalogs and the data that they serve. THis means that the server, not the
client, will retrieve the remote catalogs and render them for the requesting client and
provide an interface for retrieving the remote data, allow Hyrax to perform any subsequent
processing before returning the result to the requesting client.

Default: `false`

==== `<ingestTransformFile>` Element (optional)

This child element of ThreddsService is a specific code development option that allows
a developer to specify the fully qualified path to an XSLT file that will be used to
preprocess each THREDDS catalog file read from disk. The default version of this
file (found in
_$CATALINA_HOME/webapps/opndap/xsl/threddsCatalogIngest.xsl_) processes
the _thredds:datasetScan_ elements in each THREDDS catalog so that they
contain specific content for Hyrax:

NOTE: This is a developers option and in general is not recommended 
for use in an operational server.

==== Example Configuration Element

----
    <ThreddsService  prefix="thredds" useMemoryCache="true" allowRemote="false" />
----

=== `<GatewayService>` (optional)

Directs requests to the <<gateway-service, Gateway Service>>.

==== `<prefix>` Element (optional)

Sets localtion of the gateway service in Hyrax.
For example, if the prefix is `gateway`,
then `http://localhost:8080/opendap/gateway/` should give you the
Gateway Service page.

Default: `gateway`

==== Example Configuration Element
---- 
    <GatewayService  prefix="gateway" />
----


=== `<AllowDirectDataSourceAccess />` Element (optional)

The `<AllowDirectDataSourceAccess/>` element controls the user's
ability to directly access data sources via the Hyrax web interface. If this
element is present (and not commented out, as in the example below) a
client can get an entire data source (such as an HDF file) by
requesting it through the HTTP URL interface. By default, Hyrax ships with this option
disabled. We recommend that you leave it unchanged unless you requre that users be able
to circumvent the OPeNDAP request interface and have direct access to the data products
stored on your server.

Default: Not enabled.

==== Example Configuration Element
----
    <!-- AllowDirectDataSourceAccess / -->
----

=== `<UseDAP2ResourceUrlResponse />` Element (optional)

This element controls the Hyrax's response to a clients request for the data resource URL.
When this element is present the server will rresponed to requests for data resources URLs
by returning the (not clearly defined by a specification)
DAP2 style response. Commenting out or removing  the `<UseDAP2ResourceUrlResponse />`
element will cause the server to return the (well-defined by a specification) DAP4 DSR
response when a dataset resource URL is requested.

==== Example Configuration Element
----
    <UseDAP2ResourceUrlResponse />
----

[[bot-blocker]]
=== BotBlocker (optional)

This optional handler can be used to block access from specific IP
addresses or a range of IP addresses using regular expressions. It
turns out that many of the web crawling robots do not respect the
robots.txt file when one is provided. Since many sites do not want their
data holdings exhaustively queried by automated software, we created a
simple robot blocking handler to protect system resources from
non-compliant robots.

==== `<IpAddress>` Element

The text value of this element should be the IP address of a system
which you would like to block from accessing your service.

For example,
`<IpAddress>128.193.64.33</IPAddress>` blocks the system located at
128.193.64.33 from accessing your server.
There can be zero or more <IpAddress> elements in the <BotBlocker>.

==== `<IpMatch>` Element

The text value of this element should be the regular expression that
will be used to match the IP addresses of clients attempting to access
Hyrax.

For example, `<IpMatch>65\.55\.[012]?\d?\d\.[012]?\d?\d</IpMatch>`
matches all IP addresses beginning with 65.55 and thus blocks access for
clients whose IP addresses lie in that range. There can be zero or more
< IpMatch > elements in the Handler configuration for the BotBlocker

==== Example BotBlocker Configuration

----
    <Handler className="opendap.coreServlet.BotBlocker">
 
        <IpAddress>128.193.64.33</IpAddress>
 
        <!-- This matches all IPv4 addresses, work yours out from here.... -->
        <!--<IpMatch>[012]?\d?\d\.[012]?\d?\d\.[012]?\d?\d\.[012]?\d?\d</IpMatch> -->
 
        <!-- Any IP starting with 65.55 (MSN bots the don't respect robots.txt  -->
        <IpMatch>65\.55\.[012]?\d?\d\.[012]?\d?\d</IpMatch>
 
    </Handler>
----


=== Example olfs.xml File

----
<?xml version="1.0" encoding="UTF-8"?>
<OLFSConfig>

    <BESManager>
        <BES>
            <prefix>/</prefix>
            <host>localhost</host>
            <port>10022</port>
 
            <timeOut>300</timeOut>
 
            <adminPort>11002</adminPort>
 
            <maxResponseSize>0</maxResponseSize>
            <ClientPool maximum="200" maxCmds="2000" />
        </BES>
    </BESManager>


    <ThreddsService  prefix="thredds" useMemoryCache="true" allowRemote="true" />
    <GatewayService  prefix="gateway" useMemoryCache="true" />
    <UseDAP2ResourceUrlResponse />
    <HttpPost enabled="true" max="2000000"/>

    <!-- AddFileoutTypeSuffixToDownloadFilename / -->
    <!-- AllowDirectDataSourceAccess / -->
    <!-- PreloadNcmlIntoBes -->

    <!-- CatalogCache>
        <maxEntries>10000</maxEntries>
        <updateIntervalSeconds>10000</updateIntervalSeconds>
    </CatalogCache -->

    <!--
       'Bot Blocker' is used to block access from specific IP addresses
       and by a range of IP addresses using a regular expression.
    -->
    <!-- BotBlocker -->
    <!-- <IpAddress>127.0.0.1</IpAddress> -->
    <!-- This matches all IPv4 addresses, work yours out from here.... -->
    <!-- <IpMatch>[012]?\d?\d\.[012]?\d?\d\.[012]?\d?\d\.[012]?\d?\d</IpMatch> -->
    <!-- Any IP starting with 65.55 (MSN bots the don't respect robots.txt  -->
    <!-- <IpMatch>65\.55\.[012]?\d?\d\.[012]?\d?\d</IpMatch>   -->
    <!-- /BotBlocker -->


    <!--
      'Timer' enables or disables the generation of internal timing metrics for the OLFS
      If commented out the timing is disabled. If you want timing metrics to be output
      to the log then uncomment the Timer and set the enabled attribute's value to "true"
      WARNING: There is some performance cost to utilizing the Timer.
    -->
    <!-- Timer enabled="false" / -->


</OLFSConfig>

----
[[catalog-cache]]
==== `<CatalogCache>` Element (optional)

The catalog cache element configures the OLFS memory cache of BES
catalog responses. This cache can greatly increase server performance
for small requests. It is configured by it's two child elements,
`maxEntries` and `updateIntervalSeconds`.

* The value of `maxEntries` determines the total number of catalog
responses to hold in memory. The default value for `maxEntries` is
10000.
* The value of `updateIntervalSeconds` determines how long the catalog
update thread will sleep between updates. This value affects the server's
responsiveness to changes in its holdings. If your server's contents
changes frequently, then the `updateIntervalSeconds` should be set to a
value that will allow the server to publish new additions/deletions in a
timely manner. The `updateIntervalSeconds` default value 10000 seconds
(2.7 hours).
* If for some reason you wish to disable the `CatalogCache`, simply
remove (or comment out) the `CatalogCache` element and its children
from the `olfs.xml` file.


=== Viewers Servlet (`viewers.xml` file)

The Viewers servlet provides, for each dataset, an HTML page containing
links to Java WebStart applications and to WebServices (such as WMS)
that can be utilized in conjunction with the dataset. The Viewers
servlet is configured via the contents of the *viewers.xml* file located
in the persistent content directory _$CATALINA_HOME/content/opendap_.

==== `viewers.xml` Configuration File

===== Consists of

* *<JwsHandler>* Elements
* *<WebServiceHandler>* Elements

===== Example Configuration:

----
<ViewersConfig>
 
    <JwsHandler className="opendap.webstart.IdvViewerRequestHandler">
        <JnlpFileName>idv.jnlp</JnlpFileName>
    </JwsHandler>
 
    <JwsHandler className="opendap.webstart.NetCdfToolsViewerRequestHandler">
        <JnlpFileName>idv.jnlp</JnlpFileName>
    </JwsHandler>
 
    <JwsHandler className="opendap.webstart.AutoplotRequestHandler" />
 
    <WebServiceHandler className="opendap.viewers.NcWmsService" serviceId="ncWms" >
        <applicationName>Web Mapping Service</applicationName>
        <NcWmsService href="/ncWMS/wms" base="/ncWMS/wms" ncWmsDynamicServiceId="lds" />
    </WebServiceHandler>
 
    <WebServiceHandler className="opendap.viewers.GodivaWebService" serviceId="godiva" >
        <applicationName>Godiva WMS GUI</applicationName>
        <NcWmsService href="http://localhost:8080/ncWMS/wms" base="/ncWMS/wms" ncWmsDynamicServiceId="lds"/>
        <Godiva href="/ncWMS/godiva2.html" base="/ncWMS/godiva2.html"/>
    </WebServiceHandler>
 
</ViewersConfig>
----


=== Logging

For information about logging, please check out the
<<logging-configuration, Hyrax Logging Configuration Documentation>>.

=== Authentication and Authorization

The following sub-sections detail authentication and authorization.

==== Apache Web Server (httpd)

If your organization desires secure access and authentication layers
for Hyrax, the recommended method is to use Hyrax in conjunction the
Apache Web Server (httpd).

Most organizations that utilize secure access and authentication for
their web presence are already doing so via Apache Web Server, and Hyrax
can be integrated nicely with this existing infrastructure.

More about integrating Hyrax with Apache Web Server can be found at
these pages:

* <<apache-integration, Integrating Hyrax with Apache Web Server>>
* <<user-authentication, Configuring Hyrax and Apache for User Authentication and 
Authorization>>

==== Tomcat

Hyrax may be used with the security features implemented by Tomcat for
authentication and authorization services.
We recommend that you read carefully and understand the Tomcat
security documentation.

For Tomcat 5.x see:

* http://tomcat.apache.org/tomcat-5.5-doc/index.html[Tomcat 5.x
Documentation]
** http://tomcat.apache.org/tomcat-5.5-doc/realm-howto.html[Section 6:
Configuring/Managing User Realms]
** http://tomcat.apache.org/tomcat-5.5-doc/ssl-howto.html[Section 12:
Configuring SSL]

For Tomcat 6.x see:

* http://tomcat.apache.org/tomcat-6.0-doc/index.html[Tomcat 6.x
Documentation]
** http://tomcat.apache.org/tomcat-6.0-doc/realm-howto.html[Section 6:
Configuring/Managing User Realms]
** http://tomcat.apache.org/tomcat-6.0-doc/ssl-howto.html[Section 12:
Configuring SSL]

We also recommend that you read chapter 12 of the
http://jcp.org/aboutJava/communityprocess/final/jsr154/index.html[Java
Servlet Specification 2.4] that decribes how to configure security
constraints at the web application level.

Tomcat security requires fairly extensive additions to the _web.xml_
file. (It is important to keep in mind that altering the <__servlet__>
definitions may render your Hyrax server inoperable - please see the
previous sections that discuss this.)

Examples of security content for the web.xml file can be found in the
persistent content directory of the Hyrax server, which by default is
located at __$CATALINA_HOME/content/opendap/__.

==== Limitations

Tomcat security officially supports _context_ level authentication. This
means that you can restrict access to the collection of servlets
running in a single web application (i.e. all of the stuff
that is defined in a single _web.xml_ file). You can call out different
authentication rules for different <__url-pattern__>s within the web
application, but only clients which do not cache ANY security
information will be able to easily access the different areas.

For example, in your _web.xml_ file you might have:

----
    <security-constraint>
        <web-resource-collection>
            <web-resource-name>fnoc1</web-resource-name>
            <url-pattern>/hyrax/nc/fnoc1.txt</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <role-name>fn1</role-name>
        </auth-constraint>
    </security-constraint>
 
    <security-constraint>
        <web-resource-collection>
             <web-resource-name>fnoc2</web-resource-name>
             <url-pattern>/hyrax/nc/fnoc2.txt</url-pattern>
         </web-resource-collection>
         <auth-constraint>
             <role-name>fn2</role-name>
          </auth-constraint>
    </security-constraint>
 
    <login-config>
        <auth-method>BASIC</auth-method>
        <realm-name>MyApplicationRealm</realm-name>
    </login-config>
----

Where the security roles fn1 and fn2 (defined in the *tomcat-users.xml*
file) have no common members.

The complete URI's would be:

----
http://localhost:8080/mycontext/hyrax/nc/fnoc1.txt
http://localhost:8080/mycontext/hyrax/nc/fnoc2.txt
----

This works for clients that do not cache anything; however, if you were 
to access these URLs with a typical browser, then once you had authenticated 
for one URI, you would be locked out of the other one until you 
successfully "reset" the browser by purging all caches.

This happens because, in the exchange between Tomcat and the
client, Tomcat sends the header 
`WWW-Authenticate: Basic realm="MyApplicationRealm"`,
and the client authenticates. When the second URI is accessed, Tomcat
sends the the same authentication challenge with the same
`WWW-Authenticate` header. The client, having recently authenticated to
this _realm-name_ (defined in the <__login-config__> element in the
web.xml file - see above), resends the authentication information, and,
since it is not valid for that url pattern, the request is denied.

==== Persistence

You should be careful to back up your modified _web.xml_ file to a
location outside of the _$CATALINA_HOME/webapps/opendap_ directory, as
newly installed versions of Hyrax will overwrite it. You could use an
_XML ENTITY_ and an _entity reference_ in the _web.xml_ to cause a local
file containing the security configuration to be included in the
web.xml. For example, add the __ENTITY__ 

[source]
----
[<!ENTITY securityConfig SYSTEM "file:/fully/qualified/path/to/your/security/config.xml">]
----

to the _!DOCTYPE_ declaration at the top of the _web.xml_, and also
add an __entity reference__ (`&securityConfig;`) 
to the content of the _web-app_ element. This would cause your external
security configuration to be included in the _web.xml_ file.

._ENTITY_ configuration:
[source,xml]
----
    <?xml version="1.0" encoding="ISO-8859-1"?>

    <!DOCTYPE web-app
        PUBLIC "-//Sun Microsystems, Inc.//DTD Web Application 2.2//EN"
        "http://java.sun.com/j2ee/dtds/web-app_2_2.dtd"
        [<!ENTITY securityConfig      SYSTEM "file:/fully/qualified/path/to/your/security/config.xml">]
    >
    <web-app>

        <!--
            Loads a persistent security configuration from the content directory.
            This configuration may be empty, in which case no security constraints will be
            applied by Tomcat.
        -->
        &securityConfig;

        .
        .
        .

    </web-app>
----

This will not prevent you from losing your _web.xml_ file when a new
version of Hyrax is installed, but adding the _ENTITY_ to the new
_web.xml_ file would be easier than remembering an extensive security
configuration.

=== Compressed Responses and Tomcat

Many OPeNDAP clients accept compressed responses. This can greatly
increase the efficiency of the client/server interaction by diminishing
the number of bytes actually transmitted over "the wire." Tomcat
provides native compression support for the GZIP compression mechanism,
however it is NOT turned on by default.

The following example is based on Tomcat 5.15. We recommend that you 
carefully read the Tomcat documentation related to this topic before
proceeding:

* http://tomcat.apache.org/[Tomcat Home]
* http://tomcat.apache.org/tomcat-5.5-doc/index.html[Tomcat 5.x
documentation] (see Reference Section for the Apache Tomcat
Configuration section)
* http://tomcat.apache.org/tomcat-5.5-doc/config/http.html[Tomcat 5.x
documentation section related to compression]

==== Details

To enable compression, you will need to edit the
_$CATALINA_HOME/conf/server.xml_ file. You will need to locate the
<__Connector__> element associated with your server; typically this will
be the only <__Connector__> element whose _port_ attribute is set equal
to 8080. You will need to add or change several of its attributes to
enable compression.

With our Tomcat 7.0.76 distribution, we found this default <__Connector__>
element definition in our _server.xml_ file:

----
    <Connector
        port="8080"
        protocol="HTTP/1.1"
        connectionTimeout="20000"
        redirectPort="8443"
    />
----

You will need to add four attributes:

----
compression="force"
compressionMinSize="2048"
compressableMimeType="text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/octet-stream,application/vnd.opendap.dap4.dataset-services+xml,application/vnd.opendap.dap4.dataset-metadata+xml,application/vnd.opendap.dap4.data,application/vnd.opendap.dap4.error+xml,application/json,application/prs.coverage+json,application/rdf+xml,application/x-netcdf;ver=4,application/x-netcdf,image/tiff;application=geotiff"
----

The list of compressible MIME types includes all known response types for Hyrax.

The *compression* attribute may have the following values:

* *compression="no"* means nothing gets compressed (default if not provided).
* *compression="yes"* means only the compressible MIME types get
compressed.
* *compression="force"* means everything gets compressed (assuming the
client accepts gzip and the response is bigger than compressionMinSize)

NOTE: You MUST set *compression="force"* for compression to work with the
OPeNDAP data transport.

When finished your *Connector* element should look like this:

----
    <Connector
        port="8080"
        protocol="HTTP/1.1"
        connectionTimeout="20000"
        redirectPort="8443"
        compression="force"
        compressionMinSize="2048"
        compressableMimeType="text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/octet-stream,application/vnd.opendap.dap4.dataset-services+xml,application/vnd.opendap.dap4.dataset-metadata+xml,application/vnd.opendap.dap4.data,application/vnd.opendap.dap4.error+xml,application/json,application/prs.coverage+json,application/rdf+xml,application/x-netcdf;ver=4,application/x-netcdf,image/tiff;application=geotiff"
     />

----

Restart Tomcat for these changes to take effect.

You can verify the change by using curl as follows:
----
curl -H "Accept-Encoding: gzip" -I http://localhost:8080/opendap/data/nc/fnoc1.nc.ascii
----
NOTE: The above URL is for Hyrax running on your local system and accessing a dataset that ships with the server.

You'll know that compression is enabled if the response to the curl command contains:
----
Content-Encoding: gzip
----

NOTE: If you are using Tomcat in conjunction with the Apache Web Server
(our friend httpd) via AJP you will need to also
<<apache-compressed-responses, configure Apache to deliver compressed responses>>
Tomcat will not compress content sent over the AJP connection.*
