= Custom Module Configuration with _site.conf_

== About

Prior to Hyrax 1.15.2, if you wanted to customize a module’s configuration, 
you had to modify its _.conf_ file. 
Unfortunately, _.conf_ files do not persist through updates,
so you were responsible for restoring your custom configurations post-update.

Hyrax 1.15.2 introduces _site.conf_, a special configuration file
that persists through updates, where you can store custom module configurations. 
To start using site.conf, see its 
<<site-conf-config, configuration instruction section>>.

Beginning with release 1.15.3, Hyrax will include a template file,
_site.conf.proto_, that will include many commonly-modified settings.
For instructions on how to use the template, see its 
<<site-conf-proto-config, configuration instruction section>>.

== Theory of Operation

When you launch your server, the BES loads the module configuration files that reside within `/etc/bes/modules`.
The BES then loads _site.conf_, which resides in `/etc/bes`.

As the BES reads the custom-configured parameters that you have copied into _site.conf_,
the BES overrides the default configuration parameters that it loaded from 
the individual module configuration files. For a detailed configuration example,
see <<site-conf-example-configuration, the example configuration section>>.

[[site-conf-config]]
== _site.conf_ Configuration Instructions

The following details how you can customize a module’s configuration with _site.conf_:

1. Create _site.conf_ in `\etc\bes` with the following command:
+
....
sudo touch site.conf
....
+
2. Locate the .conf file for the module that you would like to customize.
All configuration files reside within `/etc/bes/modules`.
3. Copy the configuration parameters that you would like to customize
from the module’s configuration file into site.conf.
For a detailed configuration example, see <<site-conf-example-configuration, the next section>>.
+
NOTE: Configuration parameters are generally a key/value pair; 
for example, the default server administrator email parameter is email:support@opendap.org, 
where email is the key and support@opendap.org is the value.
+
4. Save your updates to _site.conf_.
5. Restart the server.

[[site-conf-example-configuration, site.conf Configuration Example]]
== _site.conf_ Configuration Example

The following steps detail how you can update the BES’s 
server administrator configuration parameters with your organization’s information:

1. Locate the existing server administrator configuration in `/etc/bes/bes.conf`:
+
....
BES.ServerAdministrator=email:support@opendap.org
BES.ServerAdministrator+=organization:OPeNDAP Inc.
BES.ServerAdministrator+=street:165 NW Dean Knauss Dr.
BES.ServerAdministrator+=city:Narragansett
BES.ServerAdministrator+=region:RI
BES.ServerAdministrator+=postalCode:02882
BES.ServerAdministrator+=country:US
BES.ServerAdministrator+=telephone:+1.401.575.4835
BES.ServerAdministrator+=website:http://www.opendap.org
....
+
TIP:	When adding parameters to the ServerAdministrator configuration,
notice how, following the first line, we use += instead of just +
to add new key/value pairs. += indicates to the BES that we are
adding new configuration parameters, rather than replacing those 
that were already loaded. Had we used just + in the above example, 
the only configured parameter would have been website.
+
2. Copy the above block of text from its default _.conf_ file to _site.conf_.
3. In _site.conf_, update the block of text with your organization’s information; for example...
+
....
BES.ServerAdministrator=email:smootchy@woof.org
BES.ServerAdministrator+=organization:Mogogogo Inc.
BES.ServerAdministrator+=street:165 Buzzknucker Blvd.
BES.ServerAdministrator+=city: KnockBuzzer
BES.ServerAdministrator+=region:OW
BES.ServerAdministrator+=postalCode:00007
BES.ServerAdministrator+=country:MG
BES.ServerAdministrator+=telephone:+1.800.555.1212
BES.ServerAdministrator+=website:http://www.mogogogo.org
....
+
4. Save your changes to _site.conf_.
5. Restart the server.

[[site-conf-proto-config,configuration instructions section]]
== _site.conf.proto_ Configuration Instructions

The _site.conf.proto_ template resides in `\etc\bes`.
If you want to take advantage of the template, 
copy _site.conf.proto_ into _site.conf_ with the following command:

....
cp site.conf.proto site.conf
....

Uncomment the configuration parameters that you want to modify and update them.
For a site.conf configuration example, see
<<site-conf-example-configuration, the previous section>>.