= BES Installation =
:Leonard Porrello <lporrel@gmail.com>:
{docdate}
:numbered:
:toc:

////
TODO: We should include roughtly the same level of information here for the BES as for the OLFS.
Also, we should look at the software distribution page and decide if that's the place to put the
'how to start the software' information or if this is the place. jhrg 9/15/17
////

////
== Introduction

TODO: Introduce libdap and the BES as the OLFS is introduced in the 
document Master_Hyrax_OLFS_Installation.
////

== Download

It is necessary that you download and install both the _libdap_ and _BES_ binaries.

. Visit the official OPeNDAP website and go to *Latest Release*.
. Scroll down the following page until you reach the section entitled 
  *Linux Binaries*, then continue scrolling until you
  see the heading titled *BES*.
. You need to download both the `libdap` and `BES` RPMs which should be named
  `libdap-x.x.x` and `bes-x.x.x`.
. The downloaded files should be named something like
  `libdap-x.x.x.el6.x86_64.rpm` and `bes-x.x.x.static.el6.x86_64.rpm`.

WARNING: In order to install the RPMs on your system, you *must* be running
a 64bit OS. If you are running 32bit OS, attempting to install the 
_libdap_ and _BES_ RPMs will result in errors.

////
TODO: Supplement/modify the following information as necessary. It was taken
from the Hyrax install page.
////
== Install

. **Install the libdap and bes RPMs**: +
  `sudo yum install libdap-3.x.x.rpm bes-3.x.x.rpm`

. **Test the `BES`**:
.. start it: +
   `sudo service besd start` +
   (Or use the script in _/etc/init.d with sudo_: _/etc/init.d/besd start_)
.. connect using a simple client: +
   `bescmdln`
.. get version information: +
   `BESClient> show version`
.. exit from `bescmdln`: +
   `BESClient> exit`


NOTE: *If you are upgrading to Hyrax 1.13.4 or newer from an existing installation
older than 1.13.0,* in the bes.conf file the keys _BES.CacheDir_, 
_BES.CacheSize_, and _BES.CachePrefix_ have been replaced with 
_BES.UncompressCache.dir_, _BES.UncompressCache.size_, and 
_BES.UncompressCache.prefix_ respectively. Other changes include the gateway 
cache configuration (_gateway.conf_) which now uses the keys _Gateway.Cache.dir_, 
_Gateway.Cache.size_, and _Gateway.Cache.prefix_ to configure its cache. Changing
the names enabled the BES to use separate parameters for each of its several
caches, which fixes the problem of 'cache collisions.'
