= Docker Installation (Recommended) =
:Miguel Jimenez-Urias <mjimenez@opendap.org>:
{docdate}
:numbered:
:toc:

This is the simplest way to install and use the latest release of Hyrax. 

== Prerequisites

. `Docker daemon` process is running in the background.
. You have a data folder. In this guide, we will assume it is `~/tmp/data/` .
. Your data is stored in HDF5/NetCDF4 format, csv, or any other file format for which Hyrax has a data Handler (https://www.opendap.org/software/hyrax-data-server/[see all supported file formats by Hyrax])
. OSX or Linux platform.

== Run Hyrax and serve data



. **Open a terminal and download hyrax via DockerHub**

You have two options. To download the latest official release of Hyrax data server run:

```
docker pull opendap/hyrax:latest
```
This will install the version of Hyrax as described on the official https://www.opendap.org/software/hyrax-data-server/[Hyrax data server page]. The official releases are labor intensive to produce and only happen once or twice a year. 

You can also download the absolute most recent version of Hyrax data server, i.e. that associated with the latest merged commit to the Master branch on Github, by running:

```
docker pull opendap/hyrax:snapshot
```

Both of the options above are fully tested using Travis for CI/CD, and pack with the correct versions needed to build Hyrax.


This will download the latest stable, complete build of Hyrax. 
[start=2]
. **Run Hyrax and make your data available on port `8080`**

Say, in the case you installed the `latest` using DockerHub,
```
docker run -d -h hyrax -p 8080:8080 \
--volume ~/tmp/data:/usr/share/hyrax \
--name=hyrax opendap/hyrax:latest
```

NOTE: If you are on an OSX system running on Apple silicon (M-series CPUs) docker deployment, you will need the following extra line: `--platform linux/amd64 \`.

The command above identifies the location of your data volume (`~/tmp/data`) and assigns it to `/usr/share/hyrax`, which is where Hyrax looks for data in the docker container.
[start=3]
. **Check data is available on local host**

By now, you can paste onto any browser the following url to see Hyrax's landing page
```
http://localhost:8080/opendap/hyrax
```
Make sure all your data is available and try to download some of it.

The installation of Hyrax comes with various default configutations. If you want to learn how to change the various default configurations, check the overview on the xref:Hyrax_Configuration[Configuration]

