= Aggregation
:Leonard Porrello <lporrel@gmail.com>:
:numbered:
:toc:
{docdate}

Often it is desirable to treat a collection of data files as if they were
a single dataset. Hyrax provides two different ways to do this: it enables
data providers to define _aggregations_ of files so those appear as a single
dataset and it provides a way for users to send the server a list of files
along with processing operations and receive a single amalgamated response.

In the first half of this appendix, we discuss aggregations defined by
data providers. These aggregations use a simple mark-up language
called NCML, first defined by Unidata as a way to work with NetCDF
files. Both Hyrax and the THREDDS Data Server use NCML as a tool to
describe how data files can be combined to aggregated data sets. In
the second part of this appendix, we discuss user-specified
aggregations. These aggregations currently use a new interface to the
Hyrax server.

[[NcML_Module]]
include::./handlers/BES_Modules_NcML_Module.adoc[lines="1,6..-1", leveloffset=+1]

[[join_new_aggregation]]
include::./aggregation/NCML_Module_Aggregation_JoinNew.adoc[lines="1,6..-1",leveloffset=+1]

[[join_existing_aggregation]]
include::./aggregation/NCML_Module_Aggregation_JoinExisting.adoc[lines="1,6..-1",leveloffset=+1]

[[union_aggregation]]
include::./aggregation/NCML_Module_Aggregation_Union.adoc[lines="1,6..-1",leveloffset=+1]

[[aggregation_tutorials]]
[[join_new_tutorial]]
include::./aggregation/JoinNew_Explicit_Dataset_Tutorial.adoc[lines="1,6..-1",leveloffset=+1]

[[metdata_tutorial]]
include::./aggregation/Metadata_on_Aggregations_Tutorial.adoc[lines="1,6..-1",leveloffset=+1]

[[dynamic_aggregation_tutorial]]
include::./aggregation/Dynamic_Aggregation_Tutorial.adoc[lines="1,6..-1",leveloffset=+1]

[[grid_metadata_utorial]]
include::./aggregation/Grid_Metadata_Tutorial.adoc[lines="1,6..-1",leveloffset=+1]
