= Installation =
:Leonard Porrello <lporrel@gmail.com>:
{docdate}
:numbered:
:toc:

Hyrax is a data server that implements the DAP2 and DAP4 protocols, works with a number of different data formats and supports a wide variety of customization options from tailoring the look of the server's web pages to complex server-side processing operations. This page describes how to build the server's source code. If you're working on a Linux or OS/X computer, the process is similar so we describe only the linux case; we do not support building the server on Windows operating systems.


There are broadly three ways to install and run Hyrax Data Server

- <<dockerhub, Docker Hub>>
- <<binaries, (pre-compiled) Binaries>>
- <<source, Source>>

[[dockerhub]]
include::Hyrax_DockerHub_Installation.adoc[lines="1,6..-1", leveloffset=+1]


[[binaries]]
== (pre-compiled) Binaries

Prerequisites:

. `Java>=11`
. `Tomcat>=9`

Installing a Hyrax binary release typically involves the following steps

. **Download the latest Hyrax release** (https://www.opendap.org/download-hyrax-1-17-1/[Hyrax 1.17-1]). It is composed of:
.. 2 RPM files (one for `libdap`, one for the `BES`).
.. The OLFS binary distribution file. You can also install the `OLFS Automatic robots.txt`, if available.
. **Install the `libdap` RPM.**
. **Install the `BES` RPM**.
. **Unpack the `OLFS` distribution file**, and install the `opendap.war`
  file into your Tomcat instance's `webapps` directory.
. (optional) `ncWMS2`.  You will need to use the https://reading-escience-centre.github.io/edal-java/[EDAL] web page to locate the latest `ncWMS2` “Servlet Container” software bundle as a WAR file. Install it into the same Tomcat instance as the OLFS. See https://opendap.github.io/hyrax_guide/Master_Hyrax_Guide.html#WMS_Service[here for more instructions].

TIP: The detailed download and installation instructions for Hyrax are
published on the download page for each release of the server. Find
the latest release and its associated installation details on
https://www.opendap.org/software/hyrax-data-server[the Hyrax downloads
page].

include::Hyrax_BES_Installation.adoc[lines="1,6..-1", leveloffset=+2]

include::Hyrax_OLFS_Installation.adoc[lines="1,6..-1", leveloffset=+2]


WARNING: If you are upgrading Hyrax from any previous installation older than 1.16.5, **read this!** The internal format of the `olfs.xml` file has been revised. No previous version of this file will work with Hyrax >=1.16.5. In order to upgrade your system, move your old configuration directory aside (`mv /etc/olfs ~/olfs-OLD`) and then follow the instruction to install a new `OLFS`. Once you have it installed and running you will need to review your old configuration and make the appropriate changes to the new `olfs.xml` to restore your server's behavior. The other `OLFS` configuration files have not undergone any structural changes and you may simply replace the new ones that were installed with copies of your previously working ones.

NOTE: To make the server restart with when host boots, use `systemctl enable besd` and `systemctl enable tomcat`, or `chkconfig besd on` and `chkconfig tomcat on` depending on the specifics of your Linux distribution.


[[source]]
== Hyrax GitHub Source Build

If you would like to build Hyrax from source code, you can get signed
source distributions from the
https://www.opendap.org/software/hyrax-data-server[download page]
referenced above. In addition, you can get the source code for the
server from GitHub, either using the
https://github.com/opendap/hyrax[Hyrax project] or by following the
http://docs.opendap.org/index.php/Hyrax_GitHub_Source_Build[directions
on our developer's wiki].


=== Installing Hyrax in Developer Mode

If you are interested in working on Hyrax, we maintain a wiki with 
a section devoted to http://docs.opendap.org/index.php/Developer_Info[Developer
Information] specific to our software and the development process. You can
find information there about developing your own modules for Hyrax.

== WCS Installation

The WCS 2 service comes bundled as part of Hyrax-1.14.0 and newer.
For more information about configuring WCS with your installation of Hyrax,
please refer to the <<WCS_installation_guide, WCS Installation Guide>> that
appears later in this document.


