[preface]
= Preface
:James Gallagher <jgallagher@opendap.org>:
{docdate}
:numbered:
:toc:

This manual describes the features and operation of the Hyrax data
server, a data server developed by OPeNDAP, Inc. as a reference server
for the Data Access Protocol, versions 2 and 4. the Hyrax server is
modular software with a number of _handlers_ that are loaded into a
core framework based on the contents of configuration files. Each of
the server's modules provides a distinct functional capability, such
as reading data from a certain kind of file, encoding data, or
processing data in different ways.

The text contained here was built up over several years as modules
were added to the system. Originally, the documentation was built using
a Wiki (because it was a collaborative writing tool for a distributed
group of people), where each component had a separate page. Over time,
as information was spread across many web pages and the Wiki, this became
unmanageable. We hope this new format reads more like a guide for people
who want to install and configure the server and less like a design document.

== Development Sponsored By

*http://www.nsf.gov[National Science Foundation (NSF)]* footnote:[This
material is based upon work supported by the National Science
Foundation under Grant No. 0430822. Any opinions, findings and
conclusions or recommendations expressed in this material are those of
the author(s) and do not necessarily reflect the views of the National
Science Foundation (NSF).]

*http://www.nasa.gov[National Aeronautics and Space Administration (NASA)]*

*http://www.noaa.gov[National Oceanic and Atmospheric Administration (NOAA)]*

== Acknowledgments

The High Altitude Observatory at NCAR contributed the BES framework
that is the basis for the server's data processing engine and modular
extensibility. 

Keith Seyffarth extracted the Wiki's text that forms the basis of this
manual, and Alexander Porrello and Leonard Porrello edited the text.
