
= OPeNDAP AsciiDoc site
The most recent build of some of the OPeNDAP documentation.

== Quick Start 

The
 link:https://opendap.github.io/documentation/QuickStart.html[QuickStart Guide]
 link:https://opendap.github.io/documentation/QuickStart.pdf[(PDF)]
 provides a overview of our software and its use

== User Guide

The
link:https://opendap.github.io/documentation/UserGuideComprehensive.html[UserGuide]
link:https://opendap.github.io/documentation/UserGuideComprehensive.pdf[(PDF)]
provides general information about the OPeNDAP software, the two
versions of the Data Access Protocol (DAP) and information about
access to remote data made available using DAP.

== Notes about this repository

=== Building CommonMark from AsciiDoc

Quick note about coverting to CommonMark Markdown from AsciiDoc.

To convert to CM from adoc, use 'asciidoctor' and 'pandoc' like this:

    asciidoctor -b docbook5 -o quick_start_hack QuickStart.adoc
    pandoc -f docbook -t commonmark -o quick_start.cm quick_start_hack

=== About opendap.github.io

The https://opendap.github.io site is populated with HTML and PDF
documents that are automatically built any time an AsciiDoc file in
the documentation repo is updated on the master branch.
