
= OPeNDAP AsciiDoc site
The most recent build of some of the OPeNDAP documentation.

== Quick Start 

The
 link:https://opendap.github.io/documentation/QuickStart.html[QuickStart Guide]
 link:https://opendap.github.io/documentation/QuickStart.pdf[(PDF)]
 provides a overview of our software and its use

== User Guide

The
link:https://opendap.github.io/documentation/UserGuideComprehensive.html[UserGuide]
link:https://opendap.github.io/documentation/UserGuideComprehensive.pdf[(PDF)]
provides general information about the OPeNDAP software, the two
versions of the Data Access Protocol (DAP) and information about
access to remote data made available using DAP.

== Hyrax Installation and Configuration Guide

The
link:https://opendap.github.io/documentation/Master_Hyrax_Table_of_Contents.html[Hyrax Installation and Configuration Guide]
link:https://opendap.github.io/documentation/Master_Hyrax_Table_of_Contents.pdf[(PDF)]
provides information about the Hyrax Data Server. In this guide you
will find a description of the server's featrues and all of its
configuration parameters. Also described in teh guide are other web
services that Hyrax provides, including WMS and WCS.

== Notes about this repository

=== Building CommonMark from AsciiDoc

Quick note about coverting to CommonMark Markdown from AsciiDoc.

To convert to CM from adoc, use 'asciidoctor' and 'pandoc' like this:

    asciidoctor -b docbook5 -o quick_start_hack QuickStart.adoc
    pandoc -f docbook -t commonmark -o quick_start.cm quick_start_hack

=== About opendap.github.io

The https://opendap.github.io site is populated with HTML and PDF
documents that are automatically built any time an AsciiDoc file in
the documentation repo is updated on the master branch.

=== Automaic github.io updates

See link:http://mgreau.com/posts/2016/03/28/asciidoc-to-gh-pages-with-travis-ci-docker-asciidoctor.html[Convert AsciiDoc to HTML/PDF & publish to GitHub Pages with Travis CI and Asciidoctor Docker containers] for the low-down on how the automatic updates work. 

Another take on the same sort of process - updating gh-pages from a .travis.yml file - that does not use asciidoctor: link:http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/[Automatically Update GitHub Pages with Travis].


