
= OPeNDAP AsciiDoc site
The most recent build of some of the OPeNDAP documentation.

== Quick Start 

The link:QuickStart.html[QuickStart Guide]link:QuickStart.pdf[(PDF)]
provides a overview of our software and its use

== User Guide

The link:UserGuideComprehensive.html[User
Guide]link:UserGuideComprehensive.pdf[(PDF)] provides general
information about the OPeNDAP software, the two versions of the Data
Access Protocol (DAP) and information about access to remote data made
available using DAP.

== Notes about this site

=== Building CommonMark from AsciiDoc

Quick note about ceverting to CommonMark Markdown from AsciiDoc.
(NB: We can use HTML, so this is likely not needed, but it's described
here all the same.)

While AsciiDoc is better than CommonMark, the latter is what is
actaully being used by NASA for the developer portal (well, it's one
of the formats, but CM is closest to AsciiDoc).

To convert to CM from adoc, use 'asciidoctor' and 'pandoc' like this:

    asciidoctor -b docbook5 -o quick_start_hack QuickStart.adoc
    pandoc -f docbook -t commonmark -o quick_start.cm quick_start_hack

Or just feed the HTML5 output from asciidoctor into the portal.

=== About opendap.github.io

This site is populated with HTML and PDF documents that are
automatically build any time an AsciiDoc file in the
https://github.com/opendap/documentation repo is updated on the master
branch.
