= Hyrax Installation =
:Leonard Porrello <lporrel@gmail.com>:
{docdate}
:numbered:
:toc:

== Overview ==
Installing a Hyrax binary release typically involves the following:

* https://www.opendap.org/software/hyrax-data-server[Download the
  latest Hyrax release] usually composed of:
** 2 RPM files (one for _libdap_, one for the _BES_).
** The OLFS binary distribution file.
* Install the _libdap_ RPM.
* Install the _BES_ RPM.
* Unpack the OLFS distribution file, and install the _opendap.war_
  file into your Tomcat instance's _webapps_ directory.

(The detailed download and installation instructions for Hyrax are
published on the download page for each release of the server. Find
the latest release and its associated installation details on
https://www.opendap.org/software/hyrax-data-server[the Hyrax downloads
page].)

== Source Code Builds
If you are interested in working on Hyrax or want to build the
server from source code (as opposed to using the prebuilt binaries that we
provide), you can get signed source distributions from the
https://www.opendap.org/software/hyrax-data-server[download page]
referenced above. See also the <<for-developers, For Software Developers>>
section below.

== BES Installation
Installing the _libdap_ and _BES_ binaries is straightforward.


//TODO: We should include roughtly the same level of information here for the BES as for the OLFS.
//Also, we should look at the software distribution page and decide if that's the place to put the
//'how to start the software' information or if this is the place. jhrg 9/15/17

== OLFS Installation

include::Master_Hyrax_OLFS_Installation.adoc[lines="1,6..-1", leveloffset=+1]