= Aggregation
:Leonard Porrello <lporrel@gmail.com>:
{docdate}
:numbered:
:toc:

Often it is desirable to treat a collection of data files as if they were
a single dataset. Hyrax provides two different ways to do this: it enables
data providers to define _aggregations_ of files so those appear as a single
dataset and it provides a way for users to send the server a list of files
along with processing operations and receive a single amalgamated response.

In the first half of this appendix, we discuss aggregations defined by
data providers. These aggregations use a simple mark-up language
called NCML, first defined by Unidata as a way to work with NetCDF
files. Both Hyrax and the THREDDS Data Server use NCML as a tool to
describe how data files can be combined to aggregated data sets. In
the second part of this appendix, we discuss user-specified
aggregations. These aggregations currently use a new interface to the
Hyrax server.

:tabsize: 4

include::./handlers/BES_Modules_NcML_Module.adoc[lines="1,6..-1", leveloffset=+1]
// See also the BES_Modules_NCML 

include::./aggregation/NCML_Module_Aggregation_JoinExisting.adoc[]
include::./aggregation/NCML_Module_Aggregation_JoinNew.adoc[]
include::./aggregation/NCML_Module_Aggregation_Union.adoc[]

include::./aggregation/JoinNew_Explicit_Dataset_Tutorial.adoc[]
include::./aggregation/Metadata_on_Aggregations_Tutorial.adoc[]
include::./aggregation/Dynamic_Aggregation_Tutorial.adoc[]
include::./aggregation/Grid_Metadata_Tutorial.adoc[]


// These two documents are the formal Use Case description documents. They
// should not be part of the user documentation.
// include::./aggregation/Satellite_Swath_Data_Aggregation.adoc[tabsize=4]
// include::./aggregation/Satellite_Time_Series_Aggregation.adoc[tabsize=4]

// Change this from aggregation enhancements to user-specified aggregations.
//
include::./aggregation/Aggregation_enhancements.adoc[]

// Note that this file does not include
// Use_cases_for_swath_and_time_series_aggregation.adoc
// nor does it include BES_XML_Commands.adoc
