//= OLFS Installation
//:Leonard Porrello <lporrel@gmail.com>:
//{docdate}
//:numbered:
//:toc:

== Introduction

The OLFS comes with a default configuration that is compatible with the
default configuration of the BES. If you do a default install of each
one, you should get a running Hyrax server that will be pre-populated
with test data suitable for running the integrity tests.

== Download

Follow the steps below to get the latest OLFS distribution.

. Visit the 
  https://www.opendap.org/software/hyrax-data-server#block-hyraxversions-menu[Hyrax
  Data Server Page].
. Select the most recent in the list of *Available Versions*.
. Scroll down the following page until you reach the section entitled 
  *Binaries for Hyrax x.x.x*.
. Directly underneath, you should see the OLFS download link, 
  named something like *OLFS_x.x.x._Web_Archive_File*. Click to download.
. The downloaded file should be named something like: _olfs-x.x.x-webapp.tgz_.

== Unpack

Unpack the jar file with the command `tar -xvf olfs-x.x.x-webapp.tgz`,
which will unpack a directory called _olfs-x.x.x-webapp_.

== Install

Inside the that directory, find the opendap.war file, and copy it into
the Tomcat's _webapps_ directory.

TIP: If you are working via your terminal, use the command +
`cp olfs-x.x.x-webapp/opendap.war /usr/local/apache-tomcat-6.x.x/webapps/`,
where _usr/local_ should be the directory that the Tomacat server is in.

If you're replacing an older version of the OLFS you may need do one or more of:

* Remove the directory `$CATALINA_HOME/webapps/opendap` before
restarting Tomcat.
* Determine if the existing configuration information for the
OLFS needs to be updated. If things don't work after you start Tomcat,
you should compare your local configuration with the distributed one. Typically the local configuration or the OLFS will be located in the the `/etc/olfs` directory. The file `/etc/olfs/olfs.xml` should be compared to the new default
configuration located in
`$CATALINA_HOME/webapps/opendap/WEB-INF/conf/olfs.xml` If they differ
significantly:
** Backup your current configuration and move it out of the way:
+
`cd /etc; tar -cvzf ~/olfs_backup.tgz olfs; mv olfs ~/olfs_backup`
** Restart Tomcat. If the directory `/etc/olfs` exists and can be written to by
the Tomcat user then the OLFS will copy its default configuration set to the
`/etc/olfs` location at start up.
** Compare your previous configuration files `~/olfs_backup` with the new default
ones in `/etc/olfs` and adjust the new ones accordingly.

== Starting and Stopping the OLFS/Tomcat
The OLFS component of Hyrax is web application made up of several components all of which get started when Tomcat is started, assuming that the `opendap.war` has been placed in the $CATALINA_HOME/webapps directory prior to Tomcat start.

=== Linux with a YUM installed Tomcat
If you are utilizing a YUM installed Tomcat then it should already be integrated
into the system with a `tomcat` entry in `/etc/init.d` and you should be able to:

* *Start Tomcat*: `sudo service tomcat start`
* *Stop  Tomcat*: `sudo service tomcat stop`


==== Starting Hyrax At Boot Time

In Linux, if you want Hyrax to start at boot time then you can do the following:

* Add Tomcat to the startup process:  `chkconfig --add tomcat`
* Add the BES to the startup process: `chkconfig --add besd`

Confirm that this worked by using the list function of `chkconfig`:
```
[~]$ chkconfig --list besd
besd           	0:off	1:off	2:on	3:on	4:on	5:on	6:off
[~]$ chkconfig --list tomcat
tomcat         	0:off	1:off	2:on	3:on	4:on	5:on	6:off
```

=== All systems running Tomcat from Apache distribution

If you have a Tomcat instance inflated from a downloaded distribution file
from Apache Tomcat then  you will need to configure the Tomcat environment
by setting the environment variable CATALINA_HOME to the full path of the
unpacked Tomcat distribution.

In bash: `export CATALINA_HOME = /usr/local/apache-tomcat-6.x.x`

With your shell environment configured correctly you should be able to control Tomcat like this:

* *Start Tomcat*: `$CATALINA_HOME/bin/startup.sh`
* *Stop  Tomcat*: `$CATALINA_HOME/bin/shutdown.sh`

When Tomcat starts up, it will unpack your opendap.war file and install the
webapp. You can watch this process and see other logging output by starting the
Tomcat like so:

* *Start and Watch Tomcat*: `$CATALINA_HOME/bin/startup.sh; tail -f $CATALINA_HOME/logs/catalina.out`


WARNING: If you use `ctrl-c` to stop watching the tail of the
server's output, make sure to run the command `bin/shutdown.sh`
to shutdown Tomcat. If you don't, you may get errors when you next try
to start the Tomcat server.
