= Hyrax WCS Service
:James Gallagher <jgallagher@opendap.org>:
{docdate}
:numbered:
:toc:

== Overview

Hyrax includes an optional WCS, version 2, service that can be used to
access all of the geo-referenced data available to the server that
meet the requirements of the WCS 2 specification. This appendix
describes the the kinds of data that meet these requirements along
with the installation and configuration process of the optional WCS
service. 

== Theory of Operation

The operation of the WCS service is similar to that of the
xref:WMS_Service[WMS service] described elsewhere in this manual. The
WCS service provides access to data served using DAP through a Dynamic
Service Interface. The WCS service is configured to read data served
by a DAP server (e.g., a Hyrax server) and builds the WCS responses
dynamically by accessing the data from the DAP server as those WCS
responses are requested.

However, unlike the WMS service, the WCS is more tightly integrated
into the Hyrax server's data catalog pages. There is no separate WCS
catalog, per se, and instead the Hyrax catalogs' _viewers_ pages are
used to access the WCS service interface for a particular dataset.
This level of integration simplifies configuration.

Because the links used to access the WCS service are incorporated into
the web pages provided by Hyrax, the ability to easily reference data
from other servers is not made available in the software we provide
(although it the service could be configured that way if a new catalog
system were added).

The WCS service attempts to auto-configure data sets so that the data
provider need not learn all of the details of the WCS specifications.
However, to accommodate situations where the needed metadata cannot be
read from the dataset, the WCS service can read values from a
configuration file.

== WCS Versions Supported

The Open Geospatial Consortium
(link:http://www.opengeospatial.org/[OGC]) has developed the Web
Coverage Service (WCS) as an open specification. In practice, there
are a suite of standards documents that describe different aspects of
the service, and we support several beyond the basic WCS 2.0 core specification.

TIP: The _Open Geospatial Consortium_ has many documents that describe
the concept of a _coverage_ and the different features of WCS. The
link:http://www.opengeospatial.org/standards/wcs[suite of
specifications that describe WCS] can be found on their website.

The WCS service bundled with Hyrax 1.14 supports the following WCS
specifications:

* WCS Core Interface Core, version 2.0.1
* Coverage Implementation Schema (CIS), version 1.0.1
* Range Subsetting, version 1.0.0
* KVP Protocol Binding, version 1.0.1

* XML/POST protocol Binding Extension, version 1.0.0
* XML/SOAP Protocol Binding Extension, version 1.0.0

* GeoTIFF Coverage Encoding Profile, version 1.0.1
* JPEG2000 Coverage Encoding Profile, version 1.0.0
* CF-netCDF 3.0 encoding using GML Coverage Application Schema,
  version 2.0

We have partial implementations for:

* Scaling Extension, version 1.0.0
* CRS Extension, version1.0.0

If you are interested in the _Earth Observation Application Profile_,
version 1.0.0, contact us.

== Candidate Datasets

In order for the WCS service to work with a dataset served using DAP,
that dataset must contain one or more _coverages_, dataset variables
that meet fairly strict requirements for both structure and metadata.
To qualify as a WCS coverage, a variable in a dataset must satisfy the
following criteria:

* The variable must have an associated _Spatial Reference System_
  (SRS) that describes the organization of latitude and longitude for
  the variable. The SRS also provides geo-referencing information that
  enables analysis tools to account for irregularities in the Earth's
  geoid. In practice, Hyrax is often used with data that have global
  extent and so the SRS is _WGS84_ (aka _EPSG 4396_), and the current
  version of the WCS service uses that SRS by default.
  
* The variable's fastest varying dimensions (e.g., the right-most
  dimensions in most system's representations) must be axes defined by
  the SRS (i.e., longitude and latitude) and they must match the SRS's
  axis' order.

* Other dimentions of the variable (e.g., ensamble set) must be 'to
  the left' of the dimensions defined by the SRS.

* The SRS's axes define the _range_ of the coverage; the _domain_ of
  the coverage is value of the variable. This value must have an
  associated _unit of measure_.

* The standard metadata for WCS 2.0 is limited to representing
  two-dimensional metadata, so fields in a dataset with three or more
  dimensions cannot be completely described by the
  _CoverageDescription_ response object because of limitations in the
  GML (link:http://www.opengeospatial.org/standards/gml[Geography
  Markup Language]). WCS 2.1, on the other hand, uses the CIS 1.1
  (link:http://docs.opengeospatial.org/is/09-146r6/09-146r6.html[Coverage
  Implementation Schema] standard and is more expressive with respect
  to the coverage's domain.

WARNING: The above might be wrong and is probably missing stuff. If
so, fix; if not, remove this note.

== WCS Installation (suggested)

The WCS 2 Service web application is easy to install.

To add the WCS 2 service to an running installtion of Hyrax, simply...

* Install and configure any version of Hyrax later than 1.13.5. See
  the link:https://www.opendap.org/software/hyrax-data-server[Hyrax
  download and installation page] and this guide for configuration
  information.

* Retrieve the latest stable release of the WCS 2 Service from
  link:https://www.opendap.org/software/hyrax-data-server[the Hyrax
  Server Release web page].

* Copy the WAR files _WCS-2.0.war_ into the _webapps_ directory of
  Tomcat (e.g., _/usr/share/tomcat/webaps_ if you are using the RPM
  package version of Tomcat on RedHat Linux, or more generally,
  _$CATALINA_HOME/webapps_) 

* Restart Tomcat

NOTE: While we don't test other servlet engines, users have reported
that our Web Archive files work with alternatives to Tomcat (e.g.,
GlassFish).

== Setting Dataset Fallback Values

Because WCS requires certain metadata to work (whereas DAP can
function with nothing more than a variable's name and type), our
service provides a way to use WCS with datasets that natively lack
the required WCS metadata. We do this using a pair of configuration
files. These files use a simple XML document combined with regular
expressions to establish default values for different groups of
datasets.

The configuration information is held in two different files (one that
defines a named set of default parameters for a group of files and one
that binds that set of parameters using the name) to a group of files
(using a regular expression). The first of these two files is
_wcs_service.xml_ which can be found in  _WCS-2.0/WEB-INF/conf/_ and is
shown below.

.wcs_service.xml
[source,xml,linenums]
----
<WcsService>
    <WcsCatalog className="opendap.wcs.v2_0.DynamicServiceCatalog" >
        <DynamicService name="tb13" href="http://localhost:8080/opendap/"> <!--1-->
            <DefaultSRS name="urn:ogc:def:crs:EPSG::4326"> <!--2-->
                <axisLabels>latitude longitude</axisLabels>
                <uomLabels>deg deg</uomLabels>
                <srsDimension>2</srsDimension>
            </DefaultSRS>
        </DynamicService>
    </WcsCatalog>
</WcsService>
----

<1> The _DynamicService_ definition, this links this information with the
dataset(s) describd in the _viewers.xml_ file that can be found in the
_opendap/WEB-INF/conf/_ directory.

<2> The _DefaultSRS_ element defines the axis labels, order, units and
number of dimensions for the SRS that will be used for any dataset
that does not contain an explicit SRS definition.

The second file is _viewers.xml_ found in the _opendap/WEB-INF/conf/_,
shown below.

.viewers.xml
[source,xml,linenums]
----
<ViewersConfig>
    ...
    <WebServiceHandler className="opendap.viewers.WcsService" serviceId="WCS-TB13" >
        <ApplicationName>Testbed-13 WCS Service</ApplicationName>
        <ServiceEndpoint>http://localhost:8080/WCS-2.0/</ServiceEndpoint>
        <DynamicServiceId>tb13</DynamicServiceId>	<!--1-->
       <MatchRegex>/testbed-13/.*</MatchRegex>	<!--2-->
     </WebServiceHandler>
    ...
</ViewersConfig>
----

<1> The _DynamicServiceId_ names a particular set of default SRS
values in the _wcs_service.xml_ file show above. In this example, the
name _tb13_ in both documents connects the two sections. Note that the
element is called _DynamicService_ in the _wcs_service.xml_ file.

<2> This is the regular expression that defines the data that the
Service accesses. If datasets that match the regular expression
don't have the needed metadata, they will use the defaults from the
_tb13_ section of the _wcs_service.xml_ file.

=== Recognizing and Supplying Missing Metadata
TBD

=== Reading from Servers that Require Authentication
TBD
