= Hyrax WCS Service
:James Gallagher <jgallagher@opendap.org>:
{docdate}
:numbered:
:toc:

== Overview

Hyrax includes an optional WCS-2 service (spcificlly version 2.0.1)
that can be used to
access all of the geo-referenced data available to the server that
meet the requirements of the WCS 2 specification. This appendix
describes the the kinds of data that meet these requirements along
with the installation and configuration process of the optional WCS
service. 

== Hyrax Integration

The integration of the WCS service into Hyrax is similar to that of the
xref:WMS_Service[WMS service] described elsewhere in this manual in that it
employs the concept of a DynamicService.

*WCS DynamicService*: A WCS DynamicService creates an association between a
URL path prefix in the WCS service path, and these crucial things:

- A simple coverage template for a particular file or collection of files
with similar domain coordinate characteristics.
- The URL of either a DAP server from which to get the data, or a BES
protocol reference (``bes://``) that tells the WCS engine that a direct
BES connection should be used to service the requests.
- If a BES protocol reference is provided then the rest of the href value
must be a regular expression which is applied to the dataset file
path in the server. At runtime when Hyrax uses the regex to determine if
a particular dataset should getWCS service links in it's _viewers_ page
and in its THREDDS catalog reference.

The DynamicService instances are defined in the wcs_service.xml file.

In this WCS implementation there is no separate comprehensive
WCS service with a catalog containing all of the coverages that might
be found in the server. Instead, the Hyrax catalogs' _viewers_ pages are
used to access the WCS service interface for a particular dataset.
From a programmatic access perspective the WCS endpoint URLs are easily
constructed and appear as service links associated with datasets in
the THREDDS catalogs generated by the server.

``Because the links used to access the WCS service are incorporated into
the web pages provided by Hyrax, the ability to easily reference data
from other servers is not made available in the software we provide
(although it the service could be configured that way if a new catalog
system were added).``

``This can be accomplished using either HTTP to work
with a remote DAP server, or the service can directly utilize the BES
as configured for a local Hyrax.
``

== Theory of Operation

The WCS utilizes a DAP server (e.g., a Hyrax server) to supply both
coverage metadata and binary data responses to service client WCS
requests.

In this operational model, each a DAP Dataset is considered a
(potential) WCS Coverage and the variables within a Dataset are
(potential) WCS Coverage Field entities.

The WCS service attempts to dynamically map DAP datasets to WCS
Coverages so that the data provider need not learn all of the details
of the WCS specifications. At minimum the data provider will need to
provide a simple template for each "collection" of related
dataset/coverages. The amount of detail required in a template is
a function of the metadata available within a specific datatset..

The template, called a DynamicService, provides the
domain coordinates details (Latitdue, Longitude, etc) for a group of
coverages and depending on available metadata may also need to provide
field/variable definitions. The template uses a regular expression to
create the association between the DynamicService definition (and its
coverage model) and specific files or collections of files in the DAP
server.


== WCS Versions Supported

The Open Geospatial Consortium
(link:http://www.opengeospatial.org/[OGC]) has developed the Web
Coverage Service (WCS) as an open specification. In practice, there
are a suite of standards documents that describe different aspects of
the service, and we support several beyond the basic WCS 2.0 core specification.

TIP: The _Open Geospatial Consortium_ has many documents that describe
the concept of a _coverage_ and the different features of WCS. The
link:http://www.opengeospatial.org/standards/wcs[suite of
specifications that describe WCS] can be found on their website.

The WCS service bundled with Hyrax 1.14 supports the following WCS
specifications:

* WCS Core Interface Core, version 2.0.1
* Coverage Implementation Schema (CIS), version 1.0.1
* Range Subsetting, version 1.0.0
* KVP Protocol Binding, version 1.0.1


* GeoTIFF Coverage Encoding Profile, version 1.0.1
* JPEG2000 Coverage Encoding Profile, version 1.0.0
* CF-netCDF 3.0 encoding using GML Coverage Application Schema,
  version 2.0

We have partial implementations for:

* XML/POST protocol Binding Extension, version 1.0.0
* XML/SOAP Protocol Binding Extension, version 1.0.0
* Scaling Extension, version 1.0.0
* CRS Extension, version1.0.0

If you are interested in the _Earth Observation Application Profile_,
version 1.0.0, contact us.

== Candidate Datasets

In order for the WCS service to work with a dataset served using DAP,
that dataset must contain one or more _coverages_, dataset variables
that meet fairly strict requirements for both structure and metadata.
To qualify as a WCS coverage, a variable in a dataset must satisfy the
following criteria:

* The variable must have an associated _Spatial Reference System_
  (SRS) that describes the organization of latitude and longitude for
  the variable. The SRS also provides geo-referencing information that
  enables analysis tools to account for irregularities in the Earth's
  geoid. In practice, Hyrax is often used with data that have global
  extent and so the SRS is _WGS84_ (aka _EPSG 4396_), and the current
  version of the WCS service uses that SRS by default. *TODO: WE ONLY SUPPORT EPSG-4396*
  
* The variable's fastest varying dimensions (e.g., the right-most
  dimensions in most system's representations) must be axes defined by
  the SRS (i.e., longitude and latitude) and they must match the SRS's
  axis' order.

* Other dimensions of the variable (e.g., ensemble set) must be 'to
  the left' of the dimensions defined by the SRS.

* The SRS's axes define the _domain_ of the coverage; the _range_ of
  the coverage is value of the variable. This value must have an
  associated _unit of measure_.

* The standard metadata for WCS 2.0 is limited to representing
  two-dimensional metadata, so fields in a dataset with three or more
  dimensions cannot be completely described by the
  _CoverageDescription_ response object because of limitations in the
  GML (link:http://www.opengeospatial.org/standards/gml[Geography
  Markup Language]). WCS 2.1, on the other hand, uses the CIS 1.1
  (link:http://docs.opengeospatial.org/is/09-146r6/09-146r6.html[Coverage
  Implementation Schema] standard and is more expressive with respect
  to the coverage's domain.

WARNING: The above might be wrong and is probably missing stuff. If
so, fix; if not, remove this note.

== WCS Installation (suggested)

The WCS 2 service comes bundled as part of Hyrax-1.14.0 and newer.
See the link:https://www.opendap.org/software/hyrax-data-server[Hyrax
download and installation page] and this guide for configuration
information.

Assuming that you have Hyrax installed and running on your local system
you should be able to quickly verify the WCS service is available by
pointing your browser at the default WCS endpoint
`http://localhost:8080/opendap/wcs` Which should return a browser
renderable HTML page of the _Capabilities_ document with a conspicuously
empty _Contents_
section.

NOTE: Screen grab of endpoint page here?


== Configuration
=== Setting Dataset Fallback Values

Because WCS requires certain metadata to work (whereas DAP can
function with nothing more than a variable's name and type), our
service provides a way to use WCS with datasets that natively lack
the required WCS metadata. We do this using a pair of configuration
files. These files use a simple XML document combined with regular
expressions to establish default values for different groups of
datasets.

The configuration information is held in two different files (one that
defines a named set of default parameters for a group of files and one
that binds that set of parameters using the name) to a group of files
(using a regular expression). The first of these two files is
_wcs_service.xml_ which can be found in  _WCS-2.0/WEB-INF/conf/_ and is
shown below.

.wcs_service.xml
[source,xml,linenums]
----
<WcsService>
    <WcsCatalog className="opendap.wcs.v2_0.DynamicServiceCatalog">

        <DynamicService          <!--1-->
                prefix="M2SDNXSLV"   <!--2-->
                name="MERRA-2 M2SDNXSLV WCS Service" <!--3-->
                href="bes://^/testbed-13/M2SDNXSLV\.5\.12\.4/.*$" <!--4-->
                srs="urn:ogc:def:crs:EPSG::4326" >  <!--5-->
            <DomainCoordinate name="time" dapID="time" size="1" units="Days since 1900-01-01T00:00:00.000Z" min="690" max="690"/>
            <DomainCoordinate name="latitude" dapID="lat" size="361" units="deg" min="-90" max="90"/>
            <DomainCoordinate name="longitude" dapID="lon" size="576" units="deg" min="-180" max="180"/>
        </DynamicService>
    </WcsCatalog>
</WcsService>
----

<1> The _DynamicService_ definition, provides a link between datasets matching the regex and the WCS
meta information provided in the DynamicService definition.
<2> *prefix*: This is a simple string used by the WcsCatalg implementation to
distinguish each DynamicService. Choosing a value that is in some way related to the
collection being serviced can helpful if there are problems later.
<3> *name*: A human meaningful name that will be used by the server when it creates a link to the service in the _viewers_ page.
<4> *href*:  There are two fundamental ways to define a DynamicService. One is to use an _http://_ or
_https://_  URL pointing to a Hyrax instance as  the value for the DynamicService _href_ attribute. The
other is to use a _bes://_ protocol URL. In this latter case the DynamicService will be fully integrated
into the locally running Hyrax: The data will be accessed using the BES system and the Hyrax THREDDS
catalogs and HTML pages will contain links to the various WCS endpoints. Hyrax utilizes the regular
expression stored in the body of the _bes://_ protocol _href_ to determine which services are to be
associated with which DAP Datasets.
<5> *srs*:  The _srs_ attribute defines the expected SRS for the coverages associated with this
DynamicService. The SRS defines the axis labels, order, units and
minimum number of domain coordinate dimensions and will be used for any dataset
that does not contain an explicit SRS definition. Currently only _urn:ogc:def:crs:EPSG::4326_ is
supported.

<1> The _DynamicServiceId_ names a particular set of default SRS
values in the _wcs_service.xml_ file show above. In this example, the
name _tb13_ in both documents connects the two sections. Note that the
element is called _DynamicService_ in the _wcs_service.xml_ file.

<2> This is the regular expression that defines the data that the
Service accesses. If datasets that match the regular expression
don't have the needed metadata, they will use the defaults from the
_tb13_ section of the _wcs_service.xml_ file.

==== Recognizing and Supplying Missing Metadata
TBD

==== Reading from Servers that Require Authentication
TBD
