= The HDF5 Handler
:Leonard Porrello <lporrel@gmail.com>:
{docdate}
:numbered:
:toc:

== Introduction

HDF5 handler not only supports the general mapping from HDF5 to either DAP2 or DAP4, but can also make NASA HDF5/HDF-EOS5/netCDF-4-like files follow the https://cfconventions.org/[CF conventions] so that the CF-friendly visualization clients, such as  https://www.giss.nasa.gov/tools/panoply/[Panoply], can visualize these files via Hyrax seamlessly. This feature is realized by setting a BES key _H5.EnableCF_ to _true_.  This is the default BES key setting in the Hyrax distribution.  

Four different DAP outputs can be generated via the HDF5 handler. 

Section 2 <<Highlight>> gives the highlights of these options. Section 3 to section 6 provide the detailed information on these four options.  

* <<CF Option for DAP4>>
* <<CF Option for DAP2>>
* <<Default Option for DAP4>>
* <<Default Option for DAP2>>

The HDF5 handler uses the BES keys for the hyrax data service customers to obtain the customized results and to achieve better performance. Section 7 provides the information for the most useful <<BES Keys>>, especially, section 7.3 lists the <<Default BES Key Values>> in the Hyrax source or RPM distributions. Section 8 <<Limitations>> lists the limitations of the handler at the current release. Section 9 provides the <<Miscellaneous Information>>. 


== Highlight

=== CF option for DAP4 
By definition, the CF option means the handler will follow the https://cfconventions.org/[CF conventions] to translate HDF5 to DAP. CF option is set in the Hyrax source and RPM distribution since most NASA data centers uses the CF option. To check if the CF option is used, go to _h5.conf_ and see if the BES key _H5.EnableCF_ is set to _true_.  

Key features for the CF option:

* Follow the CF naming conventions, only alphanumeric characters and underscore (‘`_`’) are allowed for a variable or attribute names. For any character not allowed by CF name conventions, change that character to underscore (‘`_`’).
* There is no group hierarchy. HDF5 groups will be flattened. In general, variable names for any non-HDF-EOS5 files should have their group path prefixed before the HDF5 variable names. The first “`/`” will be stripped off. For HDF-EOS5 files, check section 3.1 <<CF Name for DAP4>>. 
+
----
An example:
HDF5 variable name _velocity.u_ under group _geo-location_  
becomes the _geo_location_velocity_u_ in the DAP output. 
----
* The handler follows the CF conventions to translate the dimensions and coordinate variables for 
HDF-EOS5, netCDF-4 and some NASA HDF5 products. 
* HDF5 integer, floating-point and string datatypes are one-to-one mapped to DAP4. Other datatypes are ignored. 
* DAP4 coverage is supported. 

A DMR example can be found in Section 3.4 <<CF DMR Example for DAP4>>. 

=== CF Option for DAP2

The name conventions and dimension/coordinate handlings are the same as the DAP4 implementation. CF-friendly visualization clients such as https://www.giss.nasa.gov/tools/panoply/[Panoply] can visualize the HDF5 data via DAP2 successfully. Screenshots of NASA HDF5 example files via Hyrax can be found at https://hdfeos.org/zoo/hdf5_handler/index.php . 

However, due to the DAP2 limitation, HDF5 64-bit integer variables and attributes are ignored. Signed 8-bit integer is mapped to 16-bit integer since DAP2 doesn’t support signed 8-bit integer.  The handler doesn’t support DAP2 Grid. Instead, it follows the netCDF data model to use the shared dimensions for variables. 

DDS and DAS examples can be found in section 4.4 <<CF DDS and DAS Examples for DAP2>>.

=== Default Option for DAP4

To use this option, _H5.EnableCF_ must be set to _false_ in _h5.conf_. 

IMPORTANT: To obtain DAP4 output from the default option: _H5.EnableCF_ must be set to __false__ in _h5.conf_. 

This option tries to map HDF5 to DAP4 in a general way. Unlike the CF option, it is not tuned to support the NASA data products. However, instead of flattening the group hierarchy, the HDF5’s group hierarchy are kept by mapping HDF5 groups to DAP4 groups.

Moreover, when another BES key _H5.DefaultHandleDimension_ is also set to _true_ or doesn't show up, the HDF5 handler seamlessly translates the dimension names of netCDF-4 or netCDF-4-like files to DAP4 although the HDF5 data model doesn't support netCDF-4 shared dimensions. If the original netCDF-4 or netCDF-4-like files are generated to follow the CF conventions, the DAP4 output should also follow the CF as well as keeping the HDF5’s group hierarchy. 

// TODO: may add a panoply example at hdfeos.org.

In addition to mapping integer, string and floating-point data to DAP4, HDF5 compound datatype, object reference and regional reference are also mapped to DAP4.  A DMR example can be found in section 5.4 <<Default Option: DMR Example>>.

=== Default Option for DAP2

To use this option, _H5.EnableCF_ must be set to _false_ in _h5.conf_. The BES key _H5.DefaultHandleDimension_ has no effect for this option. 

IMPORTANT: To obtain DAP2 output from the default option: _H5.EnableCF_ must be set to _false_ in _h5.conf_. 

HDF5 signed 8-bit integer maps to signed 16-bit integer. 64-bit integer mapping is ignored. 

The HDF5 group hierarchy information is kept in a special DAS container _HDF_ROOT_GROUP_.  The full path of an HDF5 variable is kept as an attribute. DDS and DAS Examples can be found in section 6.4 <<Default Option: DDS and DAS Examples>>. 


== CF Option for DAP4

=== CF Name for DAP4
Other than the general name conventions described in section 2.1 <<CF Option for DAP4>>, variable names of an HDF-EOS5 multi-grid/multi-swath/multi-zonal-average file have the corresponding grid/swath/zonal-average names prefixed before the field names. Variable names of an HDF-EOS5 single grid/swath/zonal-average just use the corresponding field names. The grid/swath/zonal-average names are ignored. 

The original name and the full path of an HDF5 variable are preserved as DAP4 attributes.  A BES key can be used to turn on/off these attributes. See section 7 <<BES Keys>> for more information. Furthermore, For the HDF-EOS5 products,  the original dimension names associated with the variable are also preserved as a DAP4 attribute. This is because the HDF-EOS5 provides the dimension names and those dimension names may be changed in DAP4 output in order to follow the CF conventions. 

Although rarely in NASA HDF5 products, by following the CF name conventions, it is possible that the DAP4 variables mapped from HDF5 may share the same name and then causes an error.  To avoid this issue, the handler implements a feature to avoid this kind of name clashings. A suffix like '`_1`' is added to the the duplicated variable name. Since this rarely happens and keeping track of the name status may be expensive, a BES key is used for Hyrax service customers to turn on/off this feature. 

=== CF Datatype for DAP4

The following table lists the mapping from HDF5 to DAP4 for the CF option. 

. **HDF5 Datatype to DAP4 for CF Option**
[width="100%",cols="33%,33%,34%",options="header",]
|=======================================================================
|HDF5 data type |DAP4 data name |Notes
|8-bit unsigned integer |Byte |

|8-bit signed integer |Int8|

|16-bit unsigned integer |UInt16 |

|16-bit signed integer |Int16 |

|32-bit unsigned integer |UInt32 |

|32-bit signed integer |Int32 |

|64-bit unsigned integer |UInt64|

|64-bit signed integer |Int64 |

|32-bit floating point |Float32 |

|64-bit floating point |Float64 |

|String |String |

|Other datatypes |N/A | The handler ignores the mapping of the following datatypes: HDF5 compound, object and region references, variable length(excluding variable length string), enum,opaque, bitfield and time. |


|=======================================================================

=== CF BES Keys for DAP4

The following two BES keys must be set to _true_ to carry out the mapping of HDF5 to DAP4. In the current release,
the handler is set to run these keys as _true_ even if these two keys are omitted. For detailed description of these two keys, check section 7.1 <<Keys for Both Options>> and section 7.2 <<Keys for CF Option>>. 

----
H5.EnableCF=true
H5.EnableCFDMR=true
----

The following BES keys are also important either for performance or for correctly representing the coordinate variables. Hyrax service customers should carefully check the descriptions of these key values before changing them. The detailed description can be found at section 7.1 <<Keys for Both Options>> and 7.2 <<Keys for CF Option>>. As software improves, some settings may get changed. So hyrax service customers are encouraged to frequently check the latest https://github.com/OPENDAP/bes/blob/master/modules/hdf5_handler/README[README] and comments at the HDF5 handler configuration file https://github.com/OPENDAP/bes/blob/master/modules/hdf5_handler/h5.conf.in[h5.conf.in] at github. 

----
H5.EnableDropLongString=true
H5.EnableAddPathAttrs=true
H5.ForceFlattenNDCoorAttr=true
H5.EnableCoorattrAddPath=true
H5.MetaDataMemCacheEntries=1000
H5.EnableEOSGeoCacheFile=false
----

More BES keys and their descriptions can also be found at section 7.2 <<Keys for CF Option>>.

=== CF DMR Example for DAP4

An __h5ls__ header of an HDF-EOS5 grid file __grid_1_2d.h5__ is as follows: 
----
/                        Group
/HDFEOS                  Group
/HDFEOS/ADDITIONAL       Group
/HDFEOS/ADDITIONAL/FILE_ATTRIBUTES Group
/HDFEOS/GRIDS            Group
/HDFEOS/GRIDS/GeoGrid    Group
/HDFEOS/GRIDS/GeoGrid/Data\ Fields   Group
/HDFEOS/GRIDS/GeoGrid/Data\ Fields/temperature Dataset {4, 8}
    Attribute: units scalar
        Type:      1-byte null-terminated ASCII string
        Data:  "K"
/HDFEOS\ INFORMATION     Group
    Attribute: HDFEOSVersion scalar
        Type:      32-byte null-terminated ASCII string
        Data:  "HDFEOS_5.1.13"
/HDFEOS\ INFORMATION/StructMetadata.0 Dataset {SCALAR}
----

The corresponding DMR is:
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<Dataset xmlns="http://xml.opendap.org/ns/DAP/4.0#" dapVersion="4.0" dmrVersion="1.0" name="grid_1_2d.h5">
    <Dimension name="lon" size="8"/>
    <Dimension name="lat" size="4"/>
    <Float32 name="lon">
        <Dim name="/lon"/>
        <Attribute name="units" type="String">
            <Value>degrees_east</Value>
        </Attribute>
    </Float32>
    <Float32 name="lat">
        <Dim name="/lat"/>
        <Attribute name="units" type="String">
            <Value>degrees_north</Value>
        </Attribute>
    </Float32>
    <Float32 name="temperature">
        <Dim name="/lat"/>
        <Dim name="/lon"/>
        <Attribute name="units" type="String">
            <Value>K</Value>
        </Attribute>
        <Attribute name="origname" type="String">
            <Value>temperature</Value>
        </Attribute>
        <Attribute name="fullnamepath" type="String">
            <Value>/HDFEOS/GRIDS/GeoGrid/Data Fields/temperature</Value>
        </Attribute>
        <Attribute name="orig_dimname_list" type="String">
            <Value>YDim XDim</Value>
        </Attribute>
        <Map name="/lat"/>
        <Map name="/lon"/>
    </Float32>
    <String name="StructMetadata_0">
        <Attribute name="origname" type="String">
            <Value>StructMetadata.0</Value>
        </Attribute>
        <Attribute name="fullnamepath" type="String">
            <Value>/HDFEOS INFORMATION/StructMetadata.0</Value>
        </Attribute>
    </String>
    <Attribute name="HDFEOS" type="Container"/>
    <Attribute name="HDFEOS_ADDITIONAL" type="Container"/>
    <Attribute name="HDFEOS_ADDITIONAL_FILE_ATTRIBUTES" type="Container"/>
    <Attribute name="HDFEOS_GRIDS" type="Container"/>
    <Attribute name="HDFEOS_GRIDS_GeoGrid" type="Container"/>
    <Attribute name="HDFEOS_GRIDS_GeoGrid_Data_Fields" type="Container"/>
    <Attribute name="HDFEOS_INFORMATION" type="Container">
        <Attribute name="HDFEOSVersion" type="String">
            <Value>HDFEOS_5.1.13</Value>
        </Attribute>
        <Attribute name="fullnamepath" type="String">
            <Value>/HDFEOS INFORMATION</Value>
        </Attribute>
    </Attribute>
</Dataset>
----

Note: The CF option retrieves the values of the coordinate variables and adds them to DAP4 as variable __lat__ and variable __lon__. The variable name __StructMetadata.0__ becomes the __StructMetadata_0__. The group hierarchy is flattened. Since this is a single HDF-EOS5 grid, only the original variable name is kept. Also one can find 
----
<Map name="/lat"/>
<Map name="/lon"/>
----
under the variable __temperature__. This represents the DAP4 coverage. The original full path of variable __temperature__ can be found from the attribute __fullnamepath__ of the variable __temperature__ as
----
<Attribute name="fullnamepath" type="String">
    <Value>/HDFEOS/GRIDS/GeoGrid/Data Fields/temperature</Value>
</Attribute>
----

HDF5 group information maps to attribute container such as:
----
<Attribute name="HDFEOS" type="Container"/>
----
== CF Option for DAP2 

=== CF Name for DAP2
The same as the CF option for DAP4. See section 3.1 <<CF Name for DAP4>>.

=== CF Datatype for DAP2
The following table lists the mapping from HDF5 to DAP2 for the CF option. 

. **HDF5 Datatype to DAP2 for CF Option**
[width="100%",cols="33%,33%,34%",options="header",]
|=======================================================================
|HDF5 data type |DAP2 data name |Notes
|8-bit unsigned integer |Byte |

|8-bit signed integer |Int16|DAP2 doesn't have 8-bit signed integer type, so HDF5 8-bit signed integer maps to DAP2 16-bit integer.

|16-bit unsigned integer |UInt16 |

|16-bit signed integer |Int16 |

|32-bit unsigned integer |UInt32 |

|32-bit signed integer |Int32 |

|64-bit unsigned integer |N/A|DAP2 doesn't support 64-bit integer type.

|64-bit signed integer |N/A |

|32-bit floating point |Float32 |

|64-bit floating point |Float64 |

|String |String |

|Other datatypes |N/A |
The handler ignores the mapping of the following datatypes: HDF5 compound, variable length(excluding variable length string), object and region reference, enum,opaque, bitfield and time. |

|=======================================================================
=== CF BES Keys for DAP2

Except that BES Key __H5.EnableCFDMR__ doesn't have effect on the DAP2 mapping, the other BES key information is the same as section 3.3 <<CF BES Keys for DAP4>>.


=== CF DDS and DAS Examples for DAP2

The layout of the HDF5 file is the same as section 3.4 <<CF DMR Example for DAP4>>. 

The DDS is:
----
Dataset {
    Float32 temperature[lat = 4][lon = 8];
    String StructMetadata_0;
    Float32 lon[lon = 8];
    Float32 lat[lat = 4];
} grid_1_2d.h5;
----

The DAS is:
----
Attributes {
    HDFEOS {
    }
    HDFEOS_ADDITIONAL {
    }
    HDFEOS_ADDITIONAL_FILE_ATTRIBUTES {
    }
    HDFEOS_GRIDS {
    }
    HDFEOS_GRIDS_GeoGrid {
    }
    HDFEOS_GRIDS_GeoGrid_Data_Fields {
    }
    HDFEOS_INFORMATION {
        String HDFEOSVersion "HDFEOS_5.1.13";
        String fullnamepath "/HDFEOS INFORMATION";
    }
    temperature {
        String units "K";
        String origname "temperature";
        String fullnamepath "/HDFEOS/GRIDS/GeoGrid/Data Fields/temperature";
        String orig_dimname_list "YDim XDim";
    }
    StructMetadata_0 {
        String origname "StructMetadata.0";
        String fullnamepath "/HDFEOS INFORMATION/StructMetadata.0";
    }
    lon {
        String units "degrees_east";
    }
    lat {
        String units "degrees_north";
    }
}
----
The DDS and DAS shown in this example are equialvent to the DMR output in section 3.4 <<CF DMR Example for DAP4>> except that the DMR includes the DAP4 coverage information. However, if there are signed 8-bit integer or 64-bit integer variables in the HDF5 file, DAP4 DMR will show the exact datatype while DAP2 maps the signed 8-bit integer to 16-bit integer and ignores the mapping of 64-bit integers.


== Default Option for DAP4 

=== Default Option: DAP4 Name 
A number of non-alphanumeric characters (e.g., space, #, +, -) used in
HDF5 object names are not allowed in the names of DAP objects, object
components or in URLs. Libdap excapes these characters by replacing them with "%"
followed by the hexadecimal value of their ASCII code. For
example, "Raster Image #1" becomes "Raster%20Image%20%231". These
translations should be transparent to users of the server (but they will
be visible in the DMR and in any applications which use a client
that does not translate the identifiers back to their original form).

=== Default Option: DAP4 Datatype 
The following table lists the mapping from HDF5 to DAP4 for the default option.

. **HDF5 Datatype to DAP4 for Default Option*
[width="100%",cols="33%,33%,34%",options="header",]
|=======================================================================
|HDF5 data type |DAP4 data name |Notes
|8-bit unsigned integer |Byte |

|8-bit signed integer |Int8 |

|16-bit unsigned integer |UInt16 |

|16-bit signed integer |Int16 |

|32-bit unsigned integer |UInt32 |

|32-bit signed integer |Int32 |

|64-bit unsigned integer |Int64 |

|64-bit signed integer |UInt64 |

|32-bit floating point |Float32 |

|64-bit floating point |Float64 |

|String |String |

|Object/region reference |URL |

|Compound |Structure |HDF5 compound variable can be mapped to DAP2 under the
condition that the base members (excluding object/region references) of
compound can be mapped to DAP2.

|Other datatypes |N/A | The handler ignores the mapping of the following datatypes: HDF5 variable length(excluding variable length string), enum,opaque, bitfield and time. |

|=======================================================================

=== Default Option: DAP4 BES Keys 

The following key must be set as follows to obtain the DAP4 output for the default option and to keep the netCDF-4-like dimensions by following the netCDF data model.

----
H5.EnableCF=false
----

=== Default Option: DMR Example

A __ncdump__ header of a netCDF-4 file __nc4_group_atomic.h5__ : 
----
netcdf nc4_group_atomic {
dimensions:
	dim1 = 2 ;
variables:
	int dim1(dim1) ;
	float d1(dim1) ;

group: g1 {
  dimensions:
  	dim2 = 3 ;
  variables:
  	int dim2(dim2) ;
  	float d2(dim1, dim2) ;
  } // group g1
}
----

The corresponding DMR:

----
<?xml version="1.0" encoding="ISO-8859-1"?>
<Dataset xmlns="http://xml.opendap.org/ns/DAP/4.0#" dapVersion="4.0" dmrVersion="1.0" name="nc4_group_atomic.h5">
    <Dimension name="dim1" size="2"/>
    <Int32 name="dim1">
        <Dim name="/dim1"/>
    </Int32>
    <Float32 name="d1">
        <Dim name="/dim1"/>
    </Float32>
    <Group name="g1">
        <Dimension name="dim2" size="3"/>
        <Int32 name="dim2">
            <Dim name="/g1/dim2"/>
        </Int32>
        <Float32 name="d2">
            <Dim name="/dim1"/>
            <Dim name="/g1/dim2"/>
        </Float32>
    </Group>
</Dataset>
----

Note: Both the dimension names and the dimension sizes in the original netCDF-4 files are kept as well as the group hierarchy. 

== Default Option for DAP2

=== Default Option: DAP2 Name 
Same as section 5.1<<Default Option: DAP4 Name>>. 

=== Default Option: DAP2 Datatype 
. **HDF5 Datatype to DAP2 for Default Option**
[width="100%",cols="30%,30%,40%",options="header",]
|=======================================================================
|HDF5 data type |DAP4 data name |Notes
|8-bit unsigned integer |Byte |

|8-bit signed integer |Int16 | DAP2 doesn't have 8-bit signed integer type, so it maps to 16-bit integer.

|16-bit unsigned integer |UInt16 |

|16-bit signed integer |Int16 |

|32-bit unsigned integer |UInt32 |

|32-bit signed integer |Int32 |

|64-bit unsigned integer |N/A |DAP2 doesn't support 64-bit integer type.

|64-bit signed integer |N/A |

|32-bit floating point |Float32 |

|64-bit floating point |Float64 |

|String |String |

|Object/region reference |URL |

|Compound |Structure |HDF5 compound variable can be mapped to DAP2 under the
condition that the base members (excluding object/region references) of
compound can be mapped to DAP2.

|Other datatypes |N/A | The handler ignores the mapping of the following datatypes: HDF5 variable length(excluding variable length string), enum,opaque, bitfield and time. |

|=======================================================================

=== Default Option: DAP4 BES Keys
The following key must be set as follows to obtain the DAP2 output for the default option. Note netCDF-4-like dimensions will NOT be handled according to the netCDF data model. 

----
H5.EnableCF=false
----
=== Default Option: DDS and DAS Examples


The __h5ls__ header of the HDF5 file __d_group.h5__ : 
----
/                        Group
/a                       Group
/a/b                     Group
/a/b/c                   Group

----

Since this file doesn't have variables so the DDS is empty. 
The corresponding DAS:
----
Attributes {
    HDF5_ROOT_GROUP {
        a {
            b {
                c {
                }
            }
        }
    }
    /a/ {
        String HDF5_OBJ_FULLPATH "/a/";
    }
    /a/b/ {
        String HDF5_OBJ_FULLPATH "/a/b/";
    }
    /a/b/c/ {
        String HDF5_OBJ_FULLPATH "/a/b/c/";
    }
}

----
The attribute container __HDF5_ROOT_GROUP__ preserves the information of the group hierarchy. 

Another example show an HDF5 dataset with HDF5 compound datatype. The __h5dump__ header of the HDF5 file __d_compound.h5__:
----
HDF5 "d_compound.h5" {
GROUP "/" {
   DATASET "compound" {
      DATATYPE  H5T_COMPOUND {
         H5T_STD_I32BE "Serial number";
         H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         } "Location";
         H5T_IEEE_F64BE "Temperature (F)";
         H5T_IEEE_F64BE "Pressure (inHg)";
      }
      DATASPACE  SIMPLE { ( 4 ) / ( 4 ) }
      ATTRIBUTE "value" {
         DATATYPE  H5T_COMPOUND {
            H5T_STD_I32BE "Serial number";
            H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            } "Location";
            H5T_IEEE_F64BE "Temperature (F)";
            H5T_IEEE_F64BE "Pressure (inHg)";
         }
         DATASPACE  SIMPLE { ( 4 ) / ( 4 ) }
      }
   }
}
----

The corresponding DDS is:
----
Dataset {
    Structure {
        Int32 Serial%20number;
        String Location;
        Float64 Temperature%20%28F%29;
        Float64 Pressure%20%28inHg%29;
    } /compound[4];
} d_compound.h5;
----

Note the HDF5 compound variable array __/compound__ maps to DAP's array of Structure. The special characters inside the member names of the compound datatype are changed according to section 5.1 <<Default Option: DAP4 Name>>.

== BES Keys
In the course of supporting easy access of NASA HDF5/HDF-EOS5/netCDF4 files via Hyrax, various performance and other optimization tuning options are provided to hyrax service customers via BES keys. In this section, the descriptions for critial BES keys are provided. For the comprehensive BES key description, check the HDF5 handler configuration file https://github.com/OPENDAP/bes/blob/master/modules/hdf5_handler/h5.conf.in[h5.conf.in] at github.

=== Keys for Both Options

H5.EnableCF::
 
  When this key is set to __true__ or doesn't show up, The handler handle the HDF5 file by following the CF conventions. The handler is especially tuned to handle NASA HDF5/netCDF4/HDF-EOS5 data products. For the tested NASA products, see <<NASA Products supported and tested by the CF option of the Handler>>. 
  The key benefit of this option is to allow OPeNDAP visualization clients to display remote data seamlessly. Please visit
  http://hdfeos.org/software/hdf5_handler/doc/cf.php[here] for details.
  When this key is set to __false__, the handler handle the HDF5 file by following generic mapping from HDF5 to DAP. If the HDF5 file is a netCDF-4/HDF5 file or follows the netCDF data model and the DAP4 DMR response is requested, the handler can map the HDF5 to DAP4 by following the netCDF data model. 
  
H5.MetaDataMemCacheEntries::
Cache the DDS,DAS and DMR in the memory, the cache will start purging its objects
 only after the number of entries exceeds the number defined by this key.
The HDF5 handler can cache (in memory)DDS,DAS and DMR 
 responses it builds. If the H5.MetaDataMemCacheEntries value is zero, the cache
 is turned off. Setting the H5.MetaDataMemCacheEntries to a value greater than
 zero enables caching DDS,DAS and DMR reponses in memory. The cache
 uses a LRU policy for purging old entries; tune its behavior by
 changing the value and the CachePurgeLevel value below. Note that
 this feature is on by default.

H5.CachePurgeLevel::
CachePurgeLevel: how much of the in-memory cahce is removed when it is purged.
The H5.CachePurgeLevel key determines how much of the in-memory cache is
 removed when it is purged. The value 0.2 (the default) configures the
 software to remove the oldest 20% of items from the cache. You do not
 need to edit this to use the cache since 0.2 is the default value.

===	Keys for CF Option

H5.EnableCFDMR::
When this key is set to true, the DAP4 DMR is generated directly rather than via DDS and DAS.
 With this feature, the signed 8-bit integer and 64-bit integer mappings are kept. 
 The DMR generated by DDS and DAS will map signed 8-bit integer to signed 16-bit integer.
 Starting from 1.16.5, this key is set to true by default.

H5.EnableCoorattrAddPath::
When this key is turned on, the group path of the "coordinates" attribute values for some 
 general HDF5 products(ICESAT-2 ATL03 etc.) will be added and flattened. This is to make
 the coordinate variable names stored in the "coordinates" attribute consistent with 
 the flattened variables in the DAP output.
 
H5.ForceFlattenNDCoorAttr::
Flatten the variable path stored in the "coordinates" attribute.
If this key is turned to be true, the handler will try to flatten the
 the coordinate variable path stored inside the "coordinates" attribute.
 Currently this key only takes effect for the HDF5 file that follows
 the netCDF-4 data model when the 2-D latitude/longitude fields present.

H5.EnableDropLongString::
Drop long string variables or attributes. 
We find netCDF java has a string size limit(currently 32767). If an HDF5 string dataset
 has an individual element of which the size is greater than this limit, 
 visualization tools(Panoply etc.) that depend on
 the netCDF Java may not open the HDF5 file. So this key is set to be true to
 skip the HDF5 string of which size is greater than 32767. Users should set this
 key to false if that long string information is necessary or visualization clients
 are not used.
 Note: For the following two cases,the long string won't be dropped since the latest
 netCDF Java works fine.
 1) The size of an HDF5 string attribute exceeds 32767.
 2) Even if the total size of an HDF5 string dataset exceeds 32767, but the 
    individual string element size doesn't exceed 32767.

H5.EnableAddPathAttrs::
The original path of a variable is kept as an attribute.
When this key is set to true, the original path of the HDF5 objects is
 kept as an attribute. Users can set this key to false if users don't
 care about the absolute path of object names. Performance may get improved.
 
H5.EnableFillValueCheck::
Check if the _FillValue is within the correct datatype and data range.
We find that occassionally that the datatype of attribute _FillValue is different 
 than the datatype of the corresponding variable for some NASA HDF5 products. 
 This violates the CF conventions. So the handler
 corrects the FillValue datatype to be the corresponding variable datatype. However, the
 original value of the fillvalue may fall out of the range of the variable datatype.
 An example, var dtype: 'unsigned char';  original fillvalue dtype: 'signed char';
 original fill value: -127 is out of the range of "unsigned char". 
 If such a case occurs, we believe this is a data producer's mistake and should fail the service
 and let the data center reports this issue back to the data producer. 
 However, this may only occur for one or two variables and the data center may not 
 want to stop the hyrax service of this product. So we provide the following BES key so that 
 the data center can have an option to continue the service and may use NcML to patch the 
 wrong fillvalue until the data producer corrects it in the new release.
 By default, this key is set to true. If the fillvalue is out of the range of the variable type, 
 DAP service stops. 
 **To ignore the fillvalue check**, set this key to false. The service runs normally but
 the _Fillvalue of some variables may be wrong. netCDF-Java clients may not access the data correctly.

H5.EnableDAP4Coverage::
The handler will add DAP4 coverage information to the DMR by default. It won't affect
 the netcdf-like operations.
 
 H5.EnableCheckNameClashing::
 Check if there are variable name clashing and resolve the clashed names.
 When this key is set to true, the handler will check if
 there are name clashings among variables and attributes. 
 If name clashing occurs, the handler tries to resolve the
 name clashing by generating unique names for the clashed ones.
 For NASA HDF5 and HDF-EOS5 products, we don't see any
 name clashings for variables and attributes. In fact,
 unlike HDF4, it is very rare to have name clashing for HDF5.
 So to reduce performance overhead, we set this key to false by default. 
 Users can set this key to true if it becomes necessary.
 
H5.NoZeroSizeFullnameAttr::
 When this key is turned on, the fullnamepath attribute will
 NOT be added if the HDF5 data storage size is 0. This is
 necessary to generate correct HDF5 DMRRPP files.

H5.EscapeUTF8Attr::
When true (the default) attribute values that use UTF-8 character
 encoding are escaped in the same way as values that use the ASCII encoding. To
 enable UTF-8 in attribute values, set this to false.
 
H5.EnableDiskMetaDataCache::
If this key is set to true, the DAS will be cached into a file.
 The handler will read DAS from the cached file instead of using the HDF5 library to build since the second time.
 Since Hyrax 1.15, MetaData Store(MDS) has the similar feature as this key achieves. Users are
 encouraged to check if turning this key on can improve performance before setting this key true.

H5.EnableEOSGeoCacheFile::
HDF-EOS5 Geolocation data is cached to a file.
The latitude and longitude of an HDF-EOS5 grid will be calculated
 on-the-fly according to projection parameters stored in the HDF-EOS5
 file. The same latitude and longitude are calculated each time when
 an HDF-EOS5 grid is fetched. When the H5.EnableEOSGeoCacheFile key
 is set to true, the calculated latitude and longitude are cached to
 two flat binary files so that the same latitude and longitude will
 be obtained from the cached files starting from the second fetch.
 Several associated keys must be set correctly when this key is set
 to true.
 The description of these associated keys are: 
 
 H5.Cache.latlon.path -  An existing directory with read and write
 permissions of GeoCache files for the BES process.

 H5.Cache.latlon.prefix - The cache file prefix, it must be given
 for the cache to work.

 H5.Cache.latlon.size - The size of the cache in megabytes, the
 must must be > 0.
 
 Example:  
  H5.EnableEOSGeoCacheFile=true
  H5.Cache.latlon.path=/tmp/latlon
  H5.Cache.latlon.prefix=l
  H5.Cache.latlon.size=20000
  
 
H5.EnableDiskDataCache::

 If this key is set to true, the variable data
 will write to a binary file in the
 server. Data will be read in from the cached file since the second
 fetch. Several associated keys must be set correctly when this key
 is set to true.
 The description of these associated keys are:
  
  H5.DiskCacheDataPath - An existing directory with read and write
  permissions for the BES process.
 
  H5.DiskCacheFilePrefix - The cache file prefix, it must be given
  for the cache to work. This requirement comes from the hyrax BES.

  H5.DiskCacheSize - The size of the cache in megabytes, the value
  must must be > 0.
 
  Example:
  H5.EnableDiskDataCache=true
  H5.DiskCacheDataPath=/tmp
  H5.DiskCacheSize=100000
 
  
  H5.DiskCacheComp, H5.DiskCacheFloatOnlyComp, H5.DiskCacheCompThreshold, H5.DiskCacheCompVarSize::
  
  
   The following keys provide a way for users to fine tune the data to be cached in the disk.
  The main concern here is that users may not want to cache all variables 
  either because the disk limitations or the performance gain is less optimal for some variables.
  These BES keys will help mitigate these issues. 
  
  If H5.DiskCacheComp is true, only compressed HDF5 variables are cached. If compressed variables
  are cached, there is no data decompression time. 
  We further provide more BES keys for users to fine tune according to their specific patterns.
  
  If H5.DiskCacheFloatOnlyComp is set to be true, only floating-point variables are cached.
  
  If H5.DiskCacheCompThreshold is set, it should be a floating-point number that is greater than 1. 
  The handler will compare the compression ratio of a variable with this number, 
  only when the compression ratio is smaller than this number, the variable is cached.
  In other words, hard compressed variable usually takes longer decompression time.
  So using disk cache may greatly reduce the processing time.
  
  H5.DiskCacheCompVarSize must be a positive integer number. 
  It represents the variable size in kilobytes. 
  Only the (uncompressed) variable size that is greater than this VarSize, the variable will be cached.
  For example, if this number is 100, only the size of variable that is >100K will be cached.
  
  
=== Keys for Default Option
H5.DefaultHandleDimension::
Follow the netCDF-4 data model to handle dimensions if possible.

=== Default BES Key Values
This is the default setting for BES keys in Hyrax 1.16.5. It means that even without setting any BES key values, the handler will generate either DAP2 or DAP4 output as if these BES key values are set. As the software improves, the default setting may get changed. So check the HDF5 handler configuration file https://github.com/OPENDAP/bes/blob/master/modules/hdf5_handler/h5.conf.in[h5.conf.in] at github. 

----
H5.EnableCF=true
H5.EnableCFDMR=true
H5.ForceFlattenNDCoorAttr=true
H5.EnableCoorattrAddPath=true
H5.EnableDAP4Coverage=true
H5.EnableAddPathAttrs=true
H5.EnableDropLongString=true
H5.EnableFillValueCheck=true

H5.EscapeUTF8Attr = true
H5.EnableCheckNameClashing=false
H5.NoZeroSizeFullnameAttr=false
H5.RmConventionAttrPath=true
H5.KeepVarLeadingUnderscore=false
H5.CheckIgnoreObj=false

H5.EnablePassFileID=false
H5.MetaDataMemCacheEntries=1000

H5.EnableDiskMetaDataCache=false
H5.EnableDiskDataCache=false
H5.DiskCacheComp=false

H5.DisableStructMetaAttr=true
H5.DisableECSMetaAttr=false
H5.EnableEOSGeoCacheFile=false
----



== Limitations

CF: 

o   For DAP2, generally the mappings of 64-bit integer, time, enum, bitfield, 
        opaque, compound, array, and reference types are not supported. 
        The HDF5 variables or attributes with the above datatypes were ignored. 
	
o	 For DAP4, the mapping of HDF5 64-bit integer datatype is supported. But the other datatypes are still unsupported.
        
        o HDF5 files containing cyclic groups are not supported. 
        If such files are encountered, the handler hangs with infinite loops.

        o The handler ignores soft links, external links and comments. 
        

Default option:

o	No support for HDF5 files that have a '.' in a group/dataset
	  name.

	o For DAP2 responses, the mappings of HDF5 64-bit integer, time, enum, bitfield, and opaque datatypes are not supported. For DAP4 responses, the mapping of HDF5 64-bit integer is supported. The other datatypes are not supported.

The HDF5 files cyclic groups are not supported. The handler supports the mapping of soft links but not external links.

DAP4 coverage is not supported.


== Miscellaneous Information

=== NASA Products supported and tested by the CF option of the Handler

* HDF-EOS5 products: HIRDLS, MLS, TES, OMI, MOPITT, LANCE AMSR_2, VIIRS, MEaSURES GSSTF
* netCDF-4/HDF5 : TROP-OMI, AirMSPI, OMPS-NPP,  Atctas-CAR, many MEaSURES, Ocean color,GHRSST, ICESAT-2 ATL/Mable/GLAH 
* HDF5: SMAP, GPM, OCO2/ACOS/GOSAT, AirMSPI, Aquarius 

Note: the HDF5 handler is supposed to support any netCDF-4/HDF5 products and HDF-EOS5 products. The above just lists the data products the handler explicitly tests. 


===	Support netCDF-4  products
site.conf or change or add the file name suffix to .h5. like foo.nc4 to foo.h5 foo.nc4 to foo.nc4.h5. 
netCDF handler doesn’t support group. Arrays with shared dimensions are mapped to grid. 

===	Ignored object check
The handler provides a way for Hyrax service customers to check and list the objects in the served HDF5 file that are not mapped to DAP2. This check is valid for the DAP2 service when the CF option is on although most of the checks are also vaild for the corresponding DAP4 service.  
This key is useful for a hyrax data distributor to check the unsupported HDF5 objects by Hyrax **before** serving the data. Note this feature has not been tested much and we welcome to the feedback. To use this feature, make sure the following two BES keys to be set as follows:
----
H5.EnableCF=true
H5.CheckIgnoreObj=true
----

Check the DAS output. It will list the ignored HDF5 objects and attributes when mapping HDF5 to DAP2.

IMPORTANT: After checking the ignored HDF5 object and attribute information, make sure the H5.CheckIgnoreObj=false
----
H5.CheckIgnoreObj=false
----

== Further Reading 

* HDF5 OPeNDAP handler web page at hdfeos.org https://hdfeos.org/software/hdf5_handler.php

The web page includes pointers to the demo page to access NASA HDF5 products as well as other older but useful documents. 



